# Generated by Django 4.2.25 on 2025-10-10 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('clinical_stage', models.CharField(choices=[('newly_diagnosed', 'Newly Diagnosed'), ('relapsed_refractory', 'Relapsed/Refractory'), ('maintenance', 'Maintenance'), ('supportive', 'Supportive Care')], default='newly_diagnosed', max_length=32)),
                ('summary', models.TextField(help_text='Concise description of the case including age, stage and key features.')),
                ('risk_stratification', models.CharField(blank=True, help_text='e.g., High-risk cytogenetics, R-ISS II.', max_length=128)),
                ('lab_snapshot', models.JSONField(blank=True, default=dict, help_text='Dictionary of key laboratory values shown to the learner.')),
                ('guideline_notes', models.TextField(blank=True, help_text='Rationale, supporting evidence or pearls displayed after completion.')),
                ('expected_response', models.CharField(blank=True, choices=[('sCR', 'Stringent CR'), ('CR', 'Complete Response'), ('VGPR', 'Very Good Partial Response'), ('PR', 'Partial Response'), ('SD', 'Stable Disease'), ('PD', 'Progressive Disease')], help_text='Target IMWG response. Optional; used for feedback.', max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('recommended_regimens', models.ManyToManyField(blank=True, related_name='training_scenarios', to='clinic.regimen')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SimulationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_response', models.CharField(blank=True, choices=[('sCR', 'Stringent CR'), ('CR', 'Complete Response'), ('VGPR', 'Very Good Partial Response'), ('PR', 'Partial Response'), ('SD', 'Stable Disease'), ('PD', 'Progressive Disease')], max_length=4)),
                ('confidence', models.PositiveSmallIntegerField(default=70, help_text='Confidence in chosen plan (0-100%).')),
                ('notes', models.TextField(blank=True)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('is_guideline_aligned', models.BooleanField(default=False)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='simulator.scenario')),
                ('selected_regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.regimen')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted'],
            },
        ),
    ]
