# Generated by Django 4.2.25 on 2025-11-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_attempt_cohort_artifacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(max_length=200)),
                ('body_en', models.TextField()),
                ('title_it', models.CharField(max_length=200)),
                ('body_it', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['slug']},
        ),
    ]
