# Generated by Django 4.2.25 on 2025-11-07 23:38

from django.db import migrations


SEED_ARTICLES = [
    (
        "quickstart",
        "Quickstart workflow",
        "<p>Pick a scenario → Enable Patient Twin → Set doses within allowed ranges → Choose horizon/cohort → Run → Read KPIs → Optimize.</p>",
        "Avvio rapido",
        "<p>Seleziona scenario → Attiva Gemello Paziente → Imposta dosi entro i limiti → Scegli orizzonte/coorte → Esegui → Leggi KPI → Ottimizza.</p>",
    ),
    (
        "twin",
        "Patient Twin",
        "<p>Automatically maps R-ISS, LDH, β2M, FLC into growth/carrying parameters. Use when labs are reliable.</p>",
        "Gemello Paziente",
        "<p>Mappa automaticamente R-ISS, LDH, β2M, FLC in parametri di crescita/capacità. Usalo con lab affidabili.</p>",
    ),
    (
        "doses",
        "Dose guardrails",
        "<p>Stay inside the preset ranges. Yellow badge = borderline, red = unsafe. Use Reset to preset if values drift.</p>",
        "Limiti dose",
        "<p>Rimani nei range del preset. Badge giallo = vicino al limite, rosso = rischio. Usa Reset al preset se necessario.</p>",
    ),
    (
        "horizon_cohort",
        "Horizon & Cohort",
        "<p>Long horizons (>180d) increase stiffness. Larger cohorts (≥50) reveal uncertainty bands but take longer.</p>",
        "Orizzonte & Coorte",
        "<p>Orizzonti lunghi (&gt;180g) aumentano la rigidità numerica. Coorti grandi (≥50) mostrano bande ma richiedono più tempo.</p>",
    ),
    (
        "optimization_lab",
        "Optimization Lab",
        "<p>Runs MOTPE with efficacy/safety/exposure objectives. Constraint healthy_loss ≤ 0.25. Re-run top Pareto solutions.</p>",
        "Optimization Lab",
        "<p>Esegue MOTPE con obiettivi efficacia/sicurezza/esposizione. Vincolo perdita sani ≤ 0.25. Ri-simula le soluzioni Pareto.</p>",
    ),
    (
        "kpi_tumor_reduction",
        "Tumor reduction KPI",
        "<p>Formula: 1 - (Tumor_end / Tumor_start). 70% = partial, 90% = deep response. Raise dose or optimize if below 70%.</p>",
        "Riduzione tumorale",
        "<p>Formula: 1 - (Tumore_fine / Tumore_inizio). 70% = risposta parziale, 90% = profonda. Aumenta dose o ottimizza se sotto 70%.</p>",
    ),
    (
        "kpi_healthy_loss",
        "Healthy loss KPI",
        "<p>(Healthy_start - Healthy_end) / Healthy_start. Keep ≤0.25. Reduce doses or shorten horizon when red badge appears.</p>",
        "Perdita cellule sane",
        "<p>(Sani_inizio - Sani_fine) / Sani_inizio. Mantieni ≤0.25. Riduci le dosi o accorcia l’orizzonte quando compare il badge rosso.</p>",
    ),
    (
        "kpi_auc",
        "Drug exposure (AUC)",
        "<p>Total area under concentration curve. Lower exposure reduces toxicity but may lower efficacy—balance both.</p>",
        "Esposizione farmaco (AUC)",
        "<p>Area totale sotto la curva di concentrazione. Esposizione più bassa riduce tossicità ma potrebbe ridurre l’efficacia.</p>",
    ),
    (
        "kpi_time_to_recurrence",
        "Time to recurrence",
        "<p>First time tumor burden exceeds 50% of baseline after nadir. Long times mean durable control.</p>",
        "Tempo alla recidiva",
        "<p>Primo momento in cui il tumore supera il 50% della baseline dopo il nadir. Tempi lunghi = controllo duraturo.</p>",
    ),
    (
        "dose_ranges_lenalidomide",
        "Lenalidomide dose range",
        "<p>Default 25 mg (21/7). Guardrail: 5–30 mg. Adjust only when renal function allows.</p>",
        "Range lenalidomide",
        "<p>Default 25 mg (21/7). Guardrail: 5–30 mg. Modifica solo se la funzione renale lo permette.</p>",
    ),
    (
        "dose_ranges_bortezomib",
        "Bortezomib dose range",
        "<p>Standard 1.3 mg/m² SC weekly/biweekly. Guardrail: 0.3–1.5 mg/m².</p>",
        "Range bortezomib",
        "<p>Standard 1.3 mg/m² SC settimanale/bisettimanale. Guardrail: 0.3–1.5 mg/m².</p>",
    ),
    (
        "dose_ranges_daratumumab",
        "Daratumumab dose range",
        "<p>Loading 16 mg/kg IV. Guardrail: 8–16 mg/kg. Higher exposure increases immunosuppression.</p>",
        "Range daratumumab",
        "<p>Dose di carico 16 mg/kg IV. Guardrail: 8–16 mg/kg. Esposizioni maggiori aumentano l’immunosoppressione.</p>",
    ),
]


def seed_articles(apps, schema_editor):
    HelpArticle = apps.get_model("simulator", "HelpArticle")
    for slug, title_en, body_en, title_it, body_it in SEED_ARTICLES:
        HelpArticle.objects.update_or_create(
            slug=slug,
            defaults={
                "title_en": title_en,
                "body_en": body_en,
                "title_it": title_it,
                "body_it": body_it,
            },
        )


def unseed_articles(apps, schema_editor):  # pragma: no cover - rollback helper
    HelpArticle = apps.get_model("simulator", "HelpArticle")
    HelpArticle.objects.filter(slug__in=[slug for slug, *_ in SEED_ARTICLES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_help_articles'),
    ]

    operations = [
        migrations.RunPython(seed_articles, unseed_articles),
    ]
