# Generated by Django 4.2.25 on 2025-11-08 12:10

from django.db import migrations


ARTICLES = [
    {
        "slug": "preset",
        "title_en": "Treatment preset",
        "body_en": "<p>Selects the regimen template that pre-fills doses, bounds and schedules. Changing preset resets guardrails—use when switching from VRd to Dara-Rd.</p><p><strong>Why it matters:</strong> presets encode safe defaults so you avoid unsafe combos.</p>",
        "title_it": "Preset terapeutico",
        "body_it": "<p>Seleziona il modello di regime che pre-compila dosi, limiti e schedula. Cambiare preset ripristina i guardrail—usalo quando passi da VRd a Dara-Rd.</p><p><strong>Perché conta:</strong> i preset includono default sicuri per evitare combinazioni rischiose.</p>",
    },
    {
        "slug": "baseline_tumor_cells",
        "title_en": "Baseline tumor cells",
        "body_en": "<p>Estimated malignant plasma cell burden at t0. Typical newly diagnosed range 10<sup>9</sup>–10<sup>12</sup>.</p><p><em>Common mistake:</em> setting too low causes unrealistically fast complete responses.</p>",
        "title_it": "Cellule tumorali iniziali",
        "body_it": "<p>Stima del carico di cellule maligne al tempo zero. Range tipico alla diagnosi 10<sup>9</sup>–10<sup>12</sup>.</p><p><em>Errore comune:</em> inserire valori troppo bassi produce risposte irrealistiche.</p>",
    },
    {
        "slug": "baseline_healthy_cells",
        "title_en": "Baseline healthy plasma cells",
        "body_en": "<p>Represents marrow reserve (usually 5×10<sup>11</sup>). Drives healthy_loss metric.</p><p>Keep proportional to tumor baseline for stability.</p>",
        "title_it": "Cellule sane iniziali",
        "body_it": "<p>Rappresenta la riserva midollare (circa 5×10<sup>11</sup>). Determina la metrica di perdita sani.</p><p>Mantienila proporzionata al baseline tumorale per stabilità.</p>",
    },
    {
        "slug": "creatinine_clearance",
        "title_en": "Creatinine clearance",
        "body_en": "<p>Drives IMiD dose reductions: &lt;60 ml/min → ≤15 mg lenalidomide, &lt;30 → ≤10 mg.</p><p>Always enter latest renal labs before simulating.</p>",
        "title_it": "Clearance della creatinina",
        "body_it": "<p>Guida la riduzione degli IMiD: &lt;60 ml/min → ≤15 mg di lenalidomide, &lt;30 → ≤10 mg.</p><p>Inserisci sempre l'ultimo valore renale prima della simulazione.</p>",
    },
    {
        "slug": "neuropathy_grade",
        "title_en": "Neuropathy grade",
        "body_en": "<p>CTCAE sensory neuropathy (0–3). Grades ≥2 cap bortezomib at 1.0 mg/m².</p><p>Document baseline symptoms to justify high-dose proteasome inhibitors.</p>",
        "title_it": "Grado di neuropatia",
        "body_it": "<p>Neuropatia sensitiva CTCAE (0–3). I gradi ≥2 limitano bortezomib a 1,0 mg/m².</p><p>Registra i sintomi iniziali per motivare dosi elevate.</p>",
    },
    {
        "slug": "anc",
        "title_en": "Absolute neutrophil count",
        "body_en": "<p>Value in ×10<sup>9</sup>/L. Simulation blocks when ANC &lt;1.0.</p><p>Low ANC suggests delaying therapy or adding growth factors.</p>",
        "title_it": "Conta assoluta neutrofili",
        "body_it": "<p>Valore in ×10<sup>9</sup>/L. La simulazione si blocca quando ANC &lt;1,0.</p><p>ANC basso implica ritardare la terapia o usare fattori di crescita.</p>",
    },
    {
        "slug": "platelets",
        "title_en": "Platelets",
        "body_en": "<p>×10<sup>9</sup>/L. Below 75 triggers stop.</p><p>Use latest CBC; thrombocytopenia increases bleeding risk during VRd.</p>",
        "title_it": "Piastrine",
        "body_it": "<p>×10<sup>9</sup>/L. Sotto 75 la simulazione viene bloccata.</p><p>Usa l'ultimo emocromo: la trombocitopenia aumenta il rischio emorragico.</p>",
    },
    {
        "slug": "pregnancy",
        "title_en": "Pregnancy flag",
        "body_en": "<p>IMiDs are teratogenic. When checked, simulation refuses unsafe regimens.</p><p>Always confirm contraception status for patients of childbearing potential.</p>",
        "title_it": "Flag gravidanza",
        "body_it": "<p>Gli IMiD sono teratogeni. Se attivo, la simulazione rifiuta regimi non sicuri.</p><p>Verifica sempre lo stato contraccettivo nelle pazienti fertili.</p>",
    },
    {
        "slug": "lenalidomide_dose",
        "title_en": "Lenalidomide dose",
        "body_en": "<p>Default 25 mg (21/7). Guardrail: 5–30 mg. Adjust per renal function and toxicity.</p><p>Overshooting raises cytopenias—monitor ANC/platelets.</p>",
        "title_it": "Dose lenalidomide",
        "body_it": "<p>Default 25 mg (21/7). Guardrail: 5–30 mg. Modifica in base alla funzione renale e tossicità.</p><p>Dosi eccessive aumentano citopenie: controlla ANC/piastrine.</p>",
    },
    {
        "slug": "bortezomib_dose",
        "title_en": "Bortezomib dose",
        "body_en": "<p>Standard 1.3 mg/m² SC weekly/biweekly. Guardrail: 0.3–1.5.</p><p>High doses with neuropathy ≥2 lead to severe neuropathic pain.</p>",
        "title_it": "Dose bortezomib",
        "body_it": "<p>Standard 1,3 mg/m² SC settimanale/bisettimanale. Guardrail: 0,3–1,5.</p><p>Dosi elevate con neuropatia ≥2 portano a dolore neuropatico severo.</p>",
    },
    {
        "slug": "daratumumab_dose",
        "title_en": "Daratumumab dose",
        "body_en": "<p>Loading 16 mg/kg IV. Range 8–16 mg/kg here. Higher exposure amplifies immunosuppression.</p><p>Track IgG/ infection history.</p>",
        "title_it": "Dose daratumumab",
        "body_it": "<p>Dose di carico 16 mg/kg IV. Range 8–16 mg/kg qui. Esposizioni maggiori aumentano l'immun soppressione.</p><p>Monitora IgG e storia infettiva.</p>",
    },
    {
        "slug": "time_horizon",
        "title_en": "Simulation horizon",
        "body_en": "<p>Length in days. Recommended ≤180 to avoid stiff ODE behaviour.</p><p>Short horizons highlight induction; longer show durability.</p>",
        "title_it": "Orizzonte simulazione",
        "body_it": "<p>Durata in giorni. Consigliato ≤180 per evitare rigidità numerica.</p><p>Orizzonti brevi mostrano l'induzione; più lunghi la durabilità.</p>",
    },
    {
        "slug": "cohort_size",
        "title_en": "Virtual cohort size",
        "body_en": "<p>Number of virtual patients sampled for uncertainty bands (1,10,50,200).</p><p>Bigger cohort = longer runtime but better confidence intervals.</p>",
        "title_it": "Dimensione coorte virtuale",
        "body_it": "<p>Numero di pazienti virtuali per le bande d'incertezza (1,10,50,200).</p><p>Coorte maggiore = runtime più lungo ma intervalli più affidabili.</p>",
    },
    {
        "slug": "tumor_growth_rate",
        "title_en": "Tumor growth rate",
        "body_en": "<p>Logistic growth constant (day<sup>-1</sup>). Typical 0.015–0.03.</p><p>Use Patient Twin to auto-derive from R-ISS/LDH.</p>",
        "title_it": "Tasso crescita tumore",
        "body_it": "<p>Costante di crescita logistica (day<sup>-1</sup>). Tipico 0,015–0,03.</p><p>Usa il Gemello Paziente per derivarla da R-ISS/LDH.</p>",
    },
    {
        "slug": "healthy_growth_rate",
        "title_en": "Healthy growth rate",
        "body_en": "<p>Recovery speed for healthy plasma cells (0.01–0.02).</p><p>Lower rates mean slower marrow recovery and higher toxicity scores.</p>",
        "title_it": "Tasso crescita sane",
        "body_it": "<p>Velocità di recupero delle cellule sane (0,01–0,02).</p><p>Tassi bassi implicano recupero midollare lento e maggiore tossicità.</p>",
    },
    {
        "slug": "interaction_strength",
        "title_en": "Drug interaction strength",
        "body_en": "<p>Synergy/toxicity coupling (0–0.2). &lt;0.1 safe, 0.1–0.2 watch, &gt;0.2 unsafe.</p><p>Use Optimize to explore safer mixes.</p>",
        "title_it": "Forza interazione farmaci",
        "body_it": "<p>Accoppiamento sinergia/tossicità (0–0,2). &lt;0,1 sicuro, 0,1–0,2 attenzione, &gt;0,2 rischioso.</p><p>Usa Optimize per trovare combinazioni più sicure.</p>",
    },
    {
        "slug": "use_twin",
        "title_en": "Use Patient Twin",
        "body_en": "<p>When enabled, lab-based risk overrides auto values tagged “auto”.</p><p>Disable only for hypothetical manual scenarios.</p>",
        "title_it": "Usa Gemello Paziente",
        "body_it": "<p>Se attivo, il rischio basato sui lab sovrascrive i valori marcati “auto”.</p><p>Disattivalo solo per scenari ipotetici manuali.</p>",
    },
    {
        "slug": "seed",
        "title_en": "Random seed",
        "body_en": "<p>Optional integer to reproduce cohort sampling and solver noise.</p><p>Log seeds in artifacts for audit-friendly reruns.</p>",
        "title_it": "Seed casuale",
        "body_it": "<p>Intero opzionale per riprodurre il campionamento della coorte e il rumore del solver.</p><p>Registra il seed negli artifact per riesecuzioni verificabili.</p>",
    },
    {
        "slug": "kpi_tumor_reduction",
        "title_en": "Tumor reduction KPI",
        "body_en": "<p>Formula: 1 - (Tumor_end / Tumor_start). &gt;0.9 deep response.</p><p>If &lt;0.7, escalate therapy or shorten horizon.</p>",
        "title_it": "KPI riduzione tumorale",
        "body_it": "<p>Formula: 1 - (Tumore_fine / Tumore_inizio). &gt;0,9 risposta profonda.</p><p>Se &lt;0,7, intensifica la terapia o accorcia l'orizzonte.</p>",
    },
    {
        "slug": "kpi_healthy_loss",
        "title_en": "Healthy loss KPI",
        "body_en": "<p>(Healthy_start - Healthy_end)/Healthy_start. Keep ≤0.25.</p><p>Mitigate by lowering doses or spacing schedules.</p>",
        "title_it": "KPI perdita cellule sane",
        "body_it": "<p>(Sani_inizio - Sani_fine)/Sani_inizio. Mantieni ≤0,25.</p><p>Riduci dosi o allunga le schedulazioni per mitigare.</p>",
    },
    {
        "slug": "kpi_auc",
        "title_en": "Drug exposure (AUC)",
        "body_en": "<p>Total area under concentration curve. Lower AUC reduces toxicity but may cut efficacy.</p><p>Compare across drugs to identify drivers of toxicity.</p>",
        "title_it": "Esposizione farmaco (AUC)",
        "body_it": "<p>Area totale sotto la curva di concentrazione. AUC più bassa riduce la tossicità ma può ridurre l'efficacia.</p><p>Confronta tra farmaci per trovare i driver di tossicità.</p>",
    },
    {
        "slug": "kpi_time_to_recurrence",
        "title_en": "Time to recurrence",
        "body_en": "<p>First time tumor burden crosses 50% of baseline after nadir.</p><p>Use longer horizons or optimize if recurrence occurs early.</p>",
        "title_it": "Tempo alla recidiva",
        "body_it": "<p>Primo momento in cui il tumore supera il 50% della baseline dopo il nadir.</p><p>Usa orizzonti più lunghi o ottimizza se la recidiva è precoce.</p>",
    },
]


def seed_help_articles(apps, schema_editor):
    HelpArticle = apps.get_model("simulator", "HelpArticle")
    for entry in ARTICLES:
        HelpArticle.objects.update_or_create(
            slug=entry["slug"],
            defaults={
                "title_en": entry["title_en"],
                "body_en": entry["body_en"],
                "title_it": entry["title_it"],
                "body_it": entry["body_it"],
            },
        )


def unseed_help_articles(apps, schema_editor):  # pragma: no cover
    HelpArticle = apps.get_model("simulator", "HelpArticle")
    HelpArticle.objects.filter(slug__in=[entry["slug"] for entry in ARTICLES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_seed_help_articles'),
    ]

    operations = [
        migrations.RunPython(seed_help_articles, unseed_help_articles),
    ]
