# Generated by Django 4.2.25 on 2026-05-15 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulator', '0007_scenario_clinical_parameters'),
        ('clinic', '0005_patienttherapy_cycle_length_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterfactualRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_parameters', models.JSONField(blank=True, default=dict)),
                ('intervention_definition', models.JSONField(blank=True, default=dict)),
                ('simulation_summary', models.JSONField(blank=True, default=dict)),
                ('comparison_metrics', models.JSONField(blank=True, default=dict)),
                ('trajectory_artifact', models.TextField(blank=True)),
                ('report_artifact', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actual_therapy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterfactual_actual_runs', to='clinic.patienttherapy')),
                ('alternative_regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterfactual_alternatives', to='clinic.regimen')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientTwinState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('state_vector', models.JSONField(blank=True, default=dict)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('parameter_uncertainty', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('method', models.CharField(choices=[('initial_risk_mapping', 'Initial risk mapping'), ('residual_minimization', 'Residual minimization'), ('manual_research_override', 'Manual research override'), ('bayesian_update_placeholder', 'Bayesian update placeholder')], default='initial_risk_mapping', max_length=64)),
                ('model_version', models.CharField(max_length=64)),
                ('config_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_twin_states', to='clinic.assessment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_twin_states', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twin_states', to='clinic.patient')),
                ('source_assessments', models.ManyToManyField(blank=True, related_name='twin_state_sources', to='clinic.assessment')),
            ],
            options={
                'ordering': ['-state_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRunMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=64)),
                ('code_commit_hash', models.CharField(blank=True, max_length=128)),
                ('twin_config_hash', models.CharField(blank=True, max_length=128)),
                ('drug_preset_hashes', models.JSONField(blank=True, default=dict)),
                ('solver_name', models.CharField(max_length=128)),
                ('solver_parameters', models.JSONField(blank=True, default=dict)),
                ('input_hash', models.CharField(max_length=128)),
                ('output_hash', models.CharField(blank=True, max_length=128)),
                ('random_seed', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counterfactual_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_records', to='twin_engine.counterfactualrun')),
                ('simulation_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_metadata', to='simulator.simulationattempt')),
                ('twin_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_records', to='twin_engine.patienttwinstate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationResidual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_values', models.JSONField(blank=True, default=dict)),
                ('observed_values', models.JSONField(blank=True, default=dict)),
                ('residuals', models.JSONField(blank=True, default=dict)),
                ('normalized_residuals', models.JSONField(blank=True, default=dict)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('biomarker_weights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residual_records', to='clinic.assessment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_residuals', to='clinic.patient')),
                ('twin_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residuals', to='twin_engine.patienttwinstate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='counterfactualrun',
            name='base_twin_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterfactual_runs', to='twin_engine.patienttwinstate'),
        ),
        migrations.AddField(
            model_name='counterfactualrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_counterfactual_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='counterfactualrun',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterfactual_runs', to='clinic.patient'),
        ),
        migrations.CreateModel(
            name='CausalAssumptionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('graph_definition', models.JSONField(blank=True, default=dict)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('intervention', models.JSONField(blank=True, default=dict)),
                ('outcome', models.JSONField(blank=True, default=dict)),
                ('adjustment_set', models.JSONField(blank=True, default=list)),
                ('assumptions', models.JSONField(blank=True, default=dict)),
                ('identification_status', models.CharField(choices=[('not_identified', 'Not identified'), ('partially_identified', 'Partially identified'), ('identified_under_assumptions', 'Identified under assumptions'), ('mechanistic_only', 'Mechanistic only')], default='mechanistic_only', max_length=48)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_causal_assumption_sets', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='causal_assumption_sets', to='clinic.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='patienttwinstate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('patient',), name='unique_current_twin_state_per_patient'),
        ),
    ]
