# Generated by Django 4.2.25 on 2026-05-16 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_patienttherapy_cycle_length_days_and_more'),
        ('twin_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationresidual',
            name='stage',
            field=models.CharField(choices=[('pre_calibration', 'Pre calibration'), ('post_calibration', 'Post calibration'), ('simulation_validation', 'Simulation validation'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
        migrations.CreateModel(
            name='LongitudinalLabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('analyte', models.CharField(choices=[('HB', 'Hemoglobin'), ('WBC', 'White blood cells'), ('NEU', 'Neutrophils'), ('PLT', 'Platelets'), ('CREATININE', 'Creatinine'), ('AST', 'AST'), ('ALT', 'ALT'), ('M_PROTEIN', 'M-protein'), ('KAPPA_FLC', 'Kappa free light chains'), ('LAMBDA_FLC', 'Lambda free light chains'), ('FLC_RATIO', 'FLC ratio'), ('LDH', 'LDH'), ('BETA2M', 'Beta-2 microglobulin'), ('ALBUMIN', 'Albumin'), ('CALCIUM', 'Calcium'), ('OTHER', 'Other')], max_length=32)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('source_quality', models.CharField(choices=[('unknown', 'Unknown'), ('extracted_document', 'Extracted document'), ('clinical_record', 'Clinical record'), ('inferred_from_assessment', 'Inferred from assessment'), ('manually_curated', 'Manually curated')], default='unknown', max_length=32)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='longitudinal_lab_results', to='clinic.assessment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='longitudinal_lab_results', to='clinic.patient')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('hypertransaminasemia', 'Hypertransaminasemia'), ('neutropenia', 'Neutropenia'), ('pneumonia', 'Pneumonia'), ('upper_respiratory_infection', 'Upper respiratory infection'), ('diarrhea', 'Diarrhea'), ('neuropathy', 'Neuropathy'), ('pain', 'Pain'), ('hepatic_steatosis', 'Hepatic steatosis'), ('other', 'Other')], max_length=64)),
                ('grade', models.CharField(blank=True, max_length=32)),
                ('suspected_drug', models.CharField(blank=True, max_length=128)),
                ('observed_values', models.JSONField(blank=True, default=dict)),
                ('action_taken', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_events', to='clinic.patient')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TherapyInterruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('drug', models.CharField(max_length=64)),
                ('reason', models.CharField(choices=[('hypertransaminasemia', 'Hypertransaminasemia'), ('neutropenia', 'Neutropenia'), ('infection', 'Infection'), ('diarrhea', 'Diarrhea'), ('toxicity_unspecified', 'Toxicity unspecified'), ('planned_cycle_break', 'Planned cycle break'), ('unknown', 'Unknown')], default='unknown', max_length=64)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('action_taken', models.TextField(blank=True)),
                ('source_quality', models.CharField(default='clinical_record', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_interruptions', to='clinic.patient')),
                ('patient_therapy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interruptions', to='clinic.patienttherapy')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'start_date'], name='intr_pat_dt_idx'), models.Index(fields=['patient', 'drug', 'start_date'], name='intr_pat_drug_dt_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='therapyinterruption',
            constraint=models.UniqueConstraint(fields=('patient', 'drug', 'start_date', 'end_date'), name='unique_interruption_per_patient_drug_window'),
        ),
        migrations.AddIndex(
            model_name='longitudinallabresult',
            index=models.Index(fields=['patient', 'date'], name='lab_patient_date_idx'),
        ),
        migrations.AddIndex(
            model_name='longitudinallabresult',
            index=models.Index(fields=['patient', 'analyte', 'date'], name='lab_pat_an_dt_idx'),
        ),
        migrations.AddConstraint(
            model_name='longitudinallabresult',
            constraint=models.UniqueConstraint(fields=('patient', 'date', 'analyte'), name='unique_longitudinal_lab_per_patient_date_analyte'),
        ),
        migrations.AddIndex(
            model_name='adverseevent',
            index=models.Index(fields=['patient', 'date'], name='event_patient_date_idx'),
        ),
        migrations.AddIndex(
            model_name='adverseevent',
            index=models.Index(fields=['patient', 'event_type', 'date'], name='evt_pat_type_dt_idx'),
        ),
        migrations.AddConstraint(
            model_name='adverseevent',
            constraint=models.UniqueConstraint(fields=('patient', 'date', 'event_type'), name='unique_adverse_event_per_patient_date_type'),
        ),
    ]
