# Generated by Django 4.2.30 on 2026-08-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twin_engine', '0003_patienttwinstate_lineage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRunManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=192, unique=True)),
                ('contract_version', models.CharField(default='research-run-manifest-v1', max_length=64)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=16)),
                ('app_version', models.CharField(max_length=64)),
                ('api_version', models.CharField(max_length=64)),
                ('db_schema_version', models.CharField(max_length=128)),
                ('dataset_id', models.CharField(max_length=255)),
                ('dataset_version', models.CharField(max_length=128)),
                ('dataset_sha256', models.CharField(max_length=128)),
                ('record_subset_sha256', models.CharField(max_length=128)),
                ('model_id', models.CharField(max_length=128)),
                ('model_version', models.CharField(max_length=128)),
                ('model_card_version', models.CharField(max_length=128)),
                ('configuration_sha256', models.CharField(max_length=128)),
                ('evidence_graph_version', models.CharField(max_length=128)),
                ('validation_protocol_version', models.CharField(max_length=128)),
                ('report_template_version', models.CharField(max_length=128)),
                ('git_sha', models.CharField(max_length=128)),
                ('container_digest', models.CharField(max_length=255)),
                ('dependency_lock_sha256', models.CharField(max_length=128)),
                ('model_registry_sha256', models.CharField(max_length=128)),
                ('random_seed', models.IntegerField()),
                ('intended_use_level', models.CharField(max_length=128)),
                ('epistemic_label', models.CharField(max_length=64)),
                ('artifact_manifest', models.JSONField(default=list)),
                ('manifest_artifact_uri', models.TextField()),
                ('manifest_sha256', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='counterfactualrun',
            name='comparison_metrics_schema_version',
            field=models.CharField(default='legacy-unversioned-v0', max_length=64),
        ),
        migrations.AddField(
            model_name='counterfactualrun',
            name='intervention_schema_version',
            field=models.CharField(default='legacy-unversioned-v0', max_length=64),
        ),
        migrations.AddField(
            model_name='counterfactualrun',
            name='simulation_summary_schema_version',
            field=models.CharField(default='legacy-unversioned-v0', max_length=64),
        ),
        migrations.AddField(
            model_name='observationresidual',
            name='payload_schema_version',
            field=models.CharField(default='legacy-unversioned-v0', max_length=64),
        ),
        migrations.AddField(
            model_name='patienttwinstate',
            name='lineage_schema_version',
            field=models.CharField(default='legacy-unversioned-v0', max_length=64),
        ),
        migrations.AddField(
            model_name='patienttwinstate',
            name='parameter_uncertainty_schema_version',
            field=models.CharField(default='legacy-unversioned-v0', max_length=64),
        ),
        migrations.AddField(
            model_name='patienttwinstate',
            name='parameters_schema_version',
            field=models.CharField(default='legacy-unversioned-v0', max_length=64),
        ),
        migrations.AddField(
            model_name='patienttwinstate',
            name='state_vector_schema_version',
            field=models.CharField(default='legacy-unversioned-v0', max_length=64),
        ),
        migrations.AddField(
            model_name='simulationrunmetadata',
            name='contract_version',
            field=models.CharField(default='legacy-unversioned-v0', max_length=64),
        ),
        migrations.CreateModel(
            name='ResearchRunInvalidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_kind', models.CharField(choices=[('clinical_value', 'Clinical value'), ('dataset', 'Dataset'), ('unit_mapping', 'Unit mapping'), ('model', 'Model'), ('parameter_default', 'Parameter default'), ('dependency', 'Dependency'), ('configuration', 'Configuration')], max_length=32)),
                ('previous_identity', models.CharField(max_length=255)),
                ('replacement_identity', models.CharField(max_length=255)),
                ('change_sha256', models.CharField(max_length=128)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invalidations', to='twin_engine.researchrunmanifest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='simulationrunmetadata',
            name='manifest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='simulation_metadata', to='twin_engine.researchrunmanifest'),
        ),
        migrations.AddConstraint(
            model_name='researchruninvalidation',
            constraint=models.UniqueConstraint(fields=('manifest', 'change_kind', 'change_sha256'), name='unique_run_invalidation_change'),
        ),
        migrations.AlterField(
            model_name='counterfactualrun',
            name='comparison_metrics_schema_version',
            field=models.CharField(default='comparison-metrics-v1', max_length=64),
        ),
        migrations.AlterField(
            model_name='counterfactualrun',
            name='intervention_schema_version',
            field=models.CharField(default='intervention-v1', max_length=64),
        ),
        migrations.AlterField(
            model_name='counterfactualrun',
            name='simulation_summary_schema_version',
            field=models.CharField(default='simulation-summary-v1', max_length=64),
        ),
        migrations.AlterField(
            model_name='observationresidual',
            name='payload_schema_version',
            field=models.CharField(default='observation-residual-v1', max_length=64),
        ),
        migrations.AlterField(
            model_name='patienttwinstate',
            name='lineage_schema_version',
            field=models.CharField(default='twin-lineage-v1', max_length=64),
        ),
        migrations.AlterField(
            model_name='patienttwinstate',
            name='parameter_uncertainty_schema_version',
            field=models.CharField(default='parameter-uncertainty-v1', max_length=64),
        ),
        migrations.AlterField(
            model_name='patienttwinstate',
            name='parameters_schema_version',
            field=models.CharField(default='twin-parameters-v1', max_length=64),
        ),
        migrations.AlterField(
            model_name='patienttwinstate',
            name='state_vector_schema_version',
            field=models.CharField(default='twin-state-vector-v1', max_length=64),
        ),
        migrations.AlterField(
            model_name='simulationrunmetadata',
            name='contract_version',
            field=models.CharField(default='simulation-metadata-v1', max_length=64),
        ),
    ]
