# Generated by Django 4.2.25 on 2025-10-10 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CytogeneticAbnormality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(max_length=32, unique=True, verbose_name='MRN')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('diagnosis_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('line', models.CharField(help_text='Line of therapy (e.g. frontline, salvage).', max_length=64)),
                ('components', models.TextField(help_text='Comma-separated agents or regimen details.')),
                ('intent', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientTherapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=128)),
                ('adverse_events', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapies', to='clinic.patient')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_courses', to='clinic.regimen')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('m_protein_g_dl', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='M-Protein (g/dL)')),
                ('kappa_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Kappa (mg/L)')),
                ('lambda_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Lambda (mg/L)')),
                ('flc_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='FLC Ratio')),
                ('hemoglobin_g_dl', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Hemoglobin (g/dL)')),
                ('calcium_mg_dl', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Calcium (mg/dL)')),
                ('creatinine_mg_dl', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Creatinine (mg/dL)')),
                ('beta2m_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Beta-2 Microglobulin (mg/L)')),
                ('albumin_g_dl', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Albumin (g/dL)')),
                ('ldH_u_l', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='LDH (U/L)')),
                ('r_iss', models.CharField(blank=True, choices=[('I', 'R-ISS I'), ('II', 'R-ISS II'), ('III', 'R-ISS III')], max_length=4, verbose_name='R-ISS')),
                ('response', models.CharField(blank=True, choices=[('sCR', 'Stringent CR'), ('CR', 'Complete Response'), ('VGPR', 'Very Good Partial Response'), ('PR', 'Partial Response'), ('SD', 'Stable Disease'), ('PD', 'Progressive Disease')], max_length=4)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='clinic.patient')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PatientCytogenetics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_on', models.DateField()),
                ('method', models.CharField(blank=True, max_length=128)),
                ('abnormality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to='clinic.cytogeneticabnormality')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cytogenetics', to='clinic.patient')),
            ],
            options={
                'ordering': ['-detected_on'],
                'unique_together': {('patient', 'abnormality', 'detected_on')},
            },
        ),
    ]
