# Generated by Django 4.2.25 on 2026-01-04 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0002_regimen_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Primary owner of this patient record (minimal access control).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
