# Generated by Django 4.2.27 on 2026-03-19 21:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_patient_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(auto_now_add=True)),
                ('bone_pain_nrs', models.PositiveSmallIntegerField(blank=True, help_text='Numeric Rating Scale: 0=No pain, 10=Worst imaginable', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Bone Pain (NRS 0-10)')),
                ('bone_pain_location', models.CharField(blank=True, help_text='e.g., lumbar spine, ribs, pelvis', max_length=255, verbose_name='Pain Location')),
                ('fatigue_total', models.PositiveSmallIntegerField(blank=True, help_text='Total FACIT-F score: 0=Severe fatigue, 52=No fatigue', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(52)], verbose_name='FACIT-Fatigue Score (0-52)')),
                ('fatigue_feel_tired', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Not at all'), (1, '1 - A little bit'), (2, '2 - Somewhat'), (3, '3 - Quite a bit'), (4, '4 - Very much')], null=True, verbose_name='I feel fatigued')),
                ('fatigue_feel_weak', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Not at all'), (1, '1 - A little bit'), (2, '2 - Somewhat'), (3, '3 - Quite a bit'), (4, '4 - Very much')], null=True, verbose_name='I feel weak all over')),
                ('fatigue_feel_listless', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Not at all'), (1, '1 - A little bit'), (2, '2 - Somewhat'), (3, '3 - Quite a bit'), (4, '4 - Very much')], null=True, verbose_name='I feel listless (washed out)')),
                ('fatigue_trouble_starting', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Not at all'), (1, '1 - A little bit'), (2, '2 - Somewhat'), (3, '3 - Quite a bit'), (4, '4 - Very much')], null=True, verbose_name='I have trouble starting things')),
                ('fatigue_trouble_finishing', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Not at all'), (1, '1 - A little bit'), (2, '2 - Somewhat'), (3, '3 - Quite a bit'), (4, '4 - Very much')], null=True, verbose_name='I have trouble finishing things')),
                ('neuropathy_sensory', models.PositiveSmallIntegerField(choices=[(0, 'Grade 0 - None'), (1, 'Grade 1 - Asymptomatic; clinical or diagnostic findings only'), (2, 'Grade 2 - Moderate; limiting instrumental ADL'), (3, 'Grade 3 - Severe; limiting self-care ADL'), (4, 'Grade 4 - Life-threatening; urgent intervention indicated')], default=0, help_text='Numbness, tingling, paresthesia', verbose_name='Sensory Neuropathy (CTCAE)')),
                ('neuropathy_motor', models.PositiveSmallIntegerField(choices=[(0, 'Grade 0 - None'), (1, 'Grade 1 - Asymptomatic; clinical or diagnostic findings only'), (2, 'Grade 2 - Moderate; limiting instrumental ADL'), (3, 'Grade 3 - Severe; limiting self-care ADL'), (4, 'Grade 4 - Life-threatening; urgent intervention indicated')], default=0, help_text='Weakness, difficulty with fine motor skills', verbose_name='Motor Neuropathy (CTCAE)')),
                ('neuropathy_pain', models.PositiveSmallIntegerField(choices=[(0, 'Grade 0 - None'), (1, 'Grade 1 - Asymptomatic; clinical or diagnostic findings only'), (2, 'Grade 2 - Moderate; limiting instrumental ADL'), (3, 'Grade 3 - Severe; limiting self-care ADL'), (4, 'Grade 4 - Life-threatening; urgent intervention indicated')], default=0, help_text='Burning, shooting, electric-shock pain', verbose_name='Neuropathic Pain (CTCAE)')),
                ('crab_hypercalcemia', models.BooleanField(default=False, help_text='Serum calcium >11 mg/dL or >1 mg/dL above ULN', verbose_name='Hypercalcemia (C)')),
                ('crab_hypercalcemia_symptoms', models.CharField(blank=True, help_text='e.g., confusion, constipation, polyuria, nausea', max_length=255, verbose_name='Hypercalcemia Symptoms')),
                ('crab_renal', models.BooleanField(default=False, help_text='Creatinine >2 mg/dL or CrCl <40 mL/min', verbose_name='Renal Insufficiency (R)')),
                ('crab_renal_symptoms', models.CharField(blank=True, help_text='e.g., edema, decreased urine output, fatigue', max_length=255, verbose_name='Renal Symptoms')),
                ('crab_anemia', models.BooleanField(default=False, help_text='Hemoglobin <10 g/dL or >2 g/dL below LLN', verbose_name='Anemia (A)')),
                ('crab_anemia_symptoms', models.CharField(blank=True, help_text='e.g., fatigue, dyspnea, pallor, dizziness', max_length=255, verbose_name='Anemia Symptoms')),
                ('crab_bone', models.BooleanField(default=False, help_text='Lytic lesions on imaging or osteoporosis with fractures', verbose_name='Bone Lesions (B)')),
                ('crab_bone_symptoms', models.CharField(blank=True, help_text='e.g., fractures, vertebral compression, bone pain', max_length=255, verbose_name='Bone Symptoms')),
                ('infection_present', models.BooleanField(default=False, verbose_name='Active Infection')),
                ('infection_type', models.CharField(choices=[('none', 'No active infection'), ('respiratory', 'Respiratory (pneumonia, bronchitis, URI)'), ('urinary', 'Urinary tract infection'), ('skin', 'Skin/soft tissue infection'), ('bloodstream', 'Bloodstream infection (bacteremia/sepsis)'), ('viral', 'Viral infection (COVID, herpes, shingles)'), ('fungal', 'Fungal infection'), ('other', 'Other infection')], default='none', max_length=32, verbose_name='Infection Type')),
                ('infection_organism', models.CharField(blank=True, help_text='e.g., E. coli, S. pneumoniae, COVID-19', max_length=128, verbose_name='Organism (if known)')),
                ('infection_hospitalized', models.BooleanField(default=False, verbose_name='Required Hospitalization')),
                ('ecog_status', models.PositiveSmallIntegerField(choices=[(0, '0 - Fully active, no restrictions'), (1, '1 - Restricted in strenuous activity, ambulatory'), (2, '2 - Ambulatory, capable of self-care, unable to work'), (3, '3 - Limited self-care, confined to bed/chair >50% of day'), (4, '4 - Completely disabled, confined to bed/chair')], default=0, verbose_name='ECOG Performance Status')),
                ('appetite_loss', models.BooleanField(default=False, verbose_name='Appetite Loss')),
                ('weight_loss_pct', models.DecimalField(blank=True, decimal_places=1, help_text='Percentage weight loss in last 3 months', max_digits=4, null=True, verbose_name='Weight Loss (%)')),
                ('night_sweats', models.BooleanField(default=False, verbose_name='Night Sweats')),
                ('bruising_bleeding', models.BooleanField(default=False, verbose_name='Easy Bruising/Bleeding')),
                ('additional_notes', models.TextField(blank=True, help_text='Any other symptoms or observations', verbose_name='Additional Notes')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_assessments', to='clinic.patient')),
            ],
            options={
                'verbose_name': 'Symptom Assessment',
                'verbose_name_plural': 'Symptom Assessments',
                'ordering': ['-assessment_date'],
            },
        ),
    ]
