# Generated by Django 4.2.25 on 2026-05-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_symptomassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttherapy',
            name='cycle_length_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='days_on',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='doses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='schedule_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patienttherapy',
            name='source_quality',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('inferred', 'Inferred'), ('patient_reported', 'Patient reported'), ('clinical_record', 'Clinical record'), ('curated_research', 'Curated research')], default='unknown', max_length=32),
        ),
    ]
