from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import date
from decimal import Decimal
from typing import Any, Iterable

from django.urls import reverse

from clinic.models import Assessment, Patient, PatientTherapy

from .models import (
    AdverseEvent,
    LongitudinalLabResult,
    ObservationResidual,
    PatientTwinState,
    SimulationRunMetadata,
    TherapyInterruption,
)


CLASSIFICATION_DEFINITIONS = [
    {
        "key": "raw_structured",
        "label": "RAW STRUCTURED",
        "description": "Entered or extracted into structured patient records.",
    },
    {
        "key": "derived",
        "label": "DERIVED",
        "description": "Calculated from structured records.",
    },
    {
        "key": "simulated",
        "label": "SIMULATED",
        "description": "Generated by the mechanistic model.",
    },
    {
        "key": "heuristic",
        "label": "HEURISTIC",
        "description": "Rule-based research score or prototype signal.",
    },
    {
        "key": "missing",
        "label": "MISSING",
        "description": "Not available in structured form.",
    },
]

CLASSIFICATION_LABELS = {item["key"]: item["label"] for item in CLASSIFICATION_DEFINITIONS}

USED_IN_LABELS = {
    "initialization": "Initialization",
    "calibration": "Calibration",
    "scenario_simulation": "Scenario simulation",
    "toxicity_constraint": "Toxicity constraint",
    "uncertainty": "Uncertainty",
    "backtesting": "Backtesting",
    "robustness": "Robustness",
    "display_only": "Display only",
}

ASSESSMENT_FIELD_UNITS = {
    "m_protein_g_dl": "g/dL",
    "kappa_mg_l": "mg/L",
    "lambda_mg_l": "mg/L",
    "flc_ratio": "ratio",
    "hemoglobin_g_dl": "g/dL",
    "calcium_mg_dl": "mg/dL",
    "creatinine_mg_dl": "mg/dL",
    "beta2m_mg_l": "mg/L",
    "albumin_g_dl": "g/dL",
    "ldH_u_l": "U/L",
}


@dataclass(frozen=True)
class DataPointExplanation:
    label: str
    plain_name: str
    technical_field: str
    value_summary: str
    unit: str
    date_range: str
    n_records: int
    source_model: str
    source_table: str
    source_fields: list[str]
    data_classification: str
    used_by_model: bool
    used_in: list[str]
    why_it_matters: str
    what_missing_means: str
    next_action_if_missing: str
    source_rows_available: bool
    detail_anchor: str

    def as_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["data_classification_label"] = CLASSIFICATION_LABELS[self.data_classification]
        payload["used_in_display"] = [USED_IN_LABELS.get(value, value.replace("_", " ").title()) for value in self.used_in]
        payload["used_by_model_label"] = "Yes" if self.used_by_model else "No"
        return payload


def build_data_explainability_context(
    patient: Patient,
    *,
    current_state,
    scenario_rows: list[dict[str, Any]],
    validation_panel: dict[str, Any],
) -> dict[str, Any]:
    cockpit_url = reverse("twin_engine:research_cockpit", args=[patient.id])
    groups = [
        _build_disease_markers_group(patient, cockpit_url),
        _build_blood_markers_group(patient, cockpit_url),
        _build_liver_markers_group(patient, cockpit_url),
        _build_treatment_schedules_group(patient, cockpit_url),
        _build_interruptions_group(patient, cockpit_url),
        _build_adverse_events_group(patient, cockpit_url),
        _build_twin_state_group(patient, current_state, cockpit_url),
        _build_calibration_group(patient, current_state, validation_panel, cockpit_url),
        _build_simulated_scenarios_group(patient, scenario_rows, cockpit_url),
        _build_uncertainty_group(patient, scenario_rows, validation_panel, cockpit_url),
    ]
    return {
        "classification_legend": CLASSIFICATION_DEFINITIONS,
        "help_box_steps": [
            {
                "title": "Data status",
                "explanation": "Start here to see whether structured records exist before reading deeper explanations.",
                "href": "#one-minute-summary",
            },
            {
                "title": "What each data block means",
                "explanation": "This section explains what the data are, where they came from, and what missingness means.",
                "href": "#data-dictionary",
            },
            {
                "title": "What the model actually uses",
                "explanation": "This table shows which fields drive initialization, calibration, simulation, or diagnostics.",
                "href": "#model-status",
            },
            {
                "title": "Scenario comparison",
                "explanation": "Read the scenario cards only after the inputs and missingness rules are clear.",
                "href": "#scenario-comparison",
            },
            {
                "title": "What can I conclude?",
                "explanation": "Use this list to stay inside the allowed research interpretation boundary.",
                "href": "#conclusion-limits",
            },
            {
                "title": "What can I NOT conclude?",
                "explanation": "This list prevents accidental clinical or causal overclaiming.",
                "href": "#conclusion-limits",
            },
            {
                "title": "What should I do next?",
                "explanation": "Finish here to see the single next action with the most practical value.",
                "href": "#next-actions",
            },
        ],
        "groups": groups,
        "model_input_map": _build_model_input_map(groups),
        "scenario_explanations": _build_scenario_explanations(scenario_rows, validation_panel),
        "dictionary_lookup": {group["title"]: group for group in groups},
    }


def _build_disease_markers_group(patient: Patient, cockpit_url: str) -> dict[str, Any]:
    flc_rows = _merge_rows(
        _assessment_rows(patient, "flc_ratio", label="FLC ratio", meaning="Observed disease-activity signal from assessment record."),
        _lab_rows(patient, LongitudinalLabResult.ANALYTE_FLC_RATIO, meaning="Observed disease-activity signal from structured lab row."),
    )
    m_protein_rows = _merge_rows(
        _assessment_rows(patient, "m_protein_g_dl", label="M-protein", meaning="Observed disease-activity signal from assessment record."),
        _lab_rows(patient, LongitudinalLabResult.ANALYTE_M_PROTEIN, meaning="Observed disease-activity signal from structured lab row."),
    )
    kappa_rows = _merge_rows(
        _assessment_rows(patient, "kappa_mg_l", label="kappa FLC", meaning="Observed free light chain value from assessment record."),
        _lab_rows(patient, LongitudinalLabResult.ANALYTE_KAPPA_FLC, meaning="Observed free light chain value from structured lab row."),
    )
    lambda_rows = _merge_rows(
        _assessment_rows(patient, "lambda_mg_l", label="lambda FLC", meaning="Observed free light chain value from assessment record."),
        _lab_rows(patient, LongitudinalLabResult.ANALYTE_LAMBDA_FLC, meaning="Observed free light chain value from structured lab row."),
    )
    points = [
        _build_point(
            label="FLC ratio",
            plain_name="Free light chain ratio",
            technical_field="Assessment.flc_ratio / LongitudinalLabResult.FLC_RATIO",
            rows=flc_rows,
            unit="ratio",
            source_model="clinic.Assessment / twin_engine.LongitudinalLabResult",
            source_table="assessments / longitudinal_lab_results",
            source_fields=["flc_ratio", "analyte=FLC_RATIO"],
            data_classification="raw_structured",
            used_by_model=True,
            used_in=["initialization", "calibration", "backtesting"],
            why_it_matters="This helps the model track the direction and scale of disease-marker activity.",
            what_missing_means="Missing FLC ratio weakens disease-marker tracking and observed-vs-predicted comparison for light-chain behavior.",
            next_action_if_missing="Add or verify a structured FLC ratio row in an assessment or longitudinal lab record.",
            detail_anchor="disease-markers-details",
        ),
        _build_point(
            label="M-protein",
            plain_name="M-protein",
            technical_field="Assessment.m_protein_g_dl / LongitudinalLabResult.M_PROTEIN",
            rows=m_protein_rows,
            unit="g/dL",
            source_model="clinic.Assessment / twin_engine.LongitudinalLabResult",
            source_table="assessments / longitudinal_lab_results",
            source_fields=["m_protein_g_dl", "analyte=M_PROTEIN"],
            data_classification="raw_structured",
            used_by_model=True,
            used_in=["initialization", "calibration", "backtesting"],
            why_it_matters="This is one of the clearest disease-marker signals used to compare observed and simulated burden trends.",
            what_missing_means="Missing M-protein weakens disease-burden tracking and makes scenario comparisons harder to anchor.",
            next_action_if_missing="Add or verify a structured M-protein value.",
            detail_anchor="disease-markers-details",
        ),
        _build_point(
            label="kappa FLC",
            plain_name="Kappa free light chain",
            technical_field="Assessment.kappa_mg_l / LongitudinalLabResult.KAPPA_FLC",
            rows=kappa_rows,
            unit="mg/L",
            source_model="clinic.Assessment / twin_engine.LongitudinalLabResult",
            source_table="assessments / longitudinal_lab_results",
            source_fields=["kappa_mg_l", "analyte=KAPPA_FLC"],
            data_classification="raw_structured",
            used_by_model=True,
            used_in=["calibration", "backtesting"],
            why_it_matters="This adds detail to light-chain interpretation when present.",
            what_missing_means="Missing kappa FLC means the page can still use broader disease markers, but detailed light-chain interpretation is thinner.",
            next_action_if_missing="Add structured kappa free light chain values when available.",
            detail_anchor="disease-markers-details",
        ),
        _build_point(
            label="lambda FLC",
            plain_name="Lambda free light chain",
            technical_field="Assessment.lambda_mg_l / LongitudinalLabResult.LAMBDA_FLC",
            rows=lambda_rows,
            unit="mg/L",
            source_model="clinic.Assessment / twin_engine.LongitudinalLabResult",
            source_table="assessments / longitudinal_lab_results",
            source_fields=["lambda_mg_l", "analyte=LAMBDA_FLC"],
            data_classification="raw_structured",
            used_by_model=True,
            used_in=["calibration", "backtesting"],
            why_it_matters="This complements the free-light-chain ratio when detailed light-chain rows are available.",
            what_missing_means="Missing lambda FLC limits detailed light-chain interpretation even if broader disease markers exist.",
            next_action_if_missing="Add structured lambda free light chain values when available.",
            detail_anchor="disease-markers-details",
        ),
    ]
    counts = {point["label"]: point["n_records"] for point in points}
    return _group(
        title="Disease markers",
        plain_explanation="These are blood markers used as disease-activity signals.",
        data_source="Structured lab records and assessment records.",
        model_use="Used for initialization, calibration, and observed-vs-predicted comparison.",
        status=_status_from_counts(counts, enough_threshold=2),
        missingness_explanation=_field_count_message(
            counts,
            "Missing disease-marker fields weaken disease-marker tracking and observed-vs-predicted comparison.",
        ),
        inspect_label="Inspect details",
        detail_anchor="disease-markers-details",
        interpretation_risk="Missing FLC values weaken disease-marker tracking.",
        next_action_if_missing="Add disease-marker lab or assessment rows.",
        data_points=points,
        source_rows=_latest_rows(_merge_rows(flc_rows, m_protein_rows, kappa_rows, lambda_rows)),
        open_cockpit_href=cockpit_url + "#data-availability",
    )


def _build_blood_markers_group(patient: Patient, cockpit_url: str) -> dict[str, Any]:
    hb_rows = _merge_rows(
        _assessment_rows(patient, "hemoglobin_g_dl", label="hemoglobin", meaning="Observed blood-reserve marker from assessment record."),
        _lab_rows(patient, LongitudinalLabResult.ANALYTE_HB, meaning="Observed blood-reserve marker from structured lab row."),
    )
    wbc_rows = _lab_rows(patient, LongitudinalLabResult.ANALYTE_WBC, meaning="Observed white-cell row from structured lab data.")
    neu_rows = _lab_rows(patient, LongitudinalLabResult.ANALYTE_NEU, meaning="Observed neutrophil row from structured lab data.")
    plt_rows = _lab_rows(patient, LongitudinalLabResult.ANALYTE_PLT, meaning="Observed platelet row from structured lab data.")
    points = [
        _build_point(
            label="hemoglobin",
            plain_name="Hemoglobin",
            technical_field="Assessment.hemoglobin_g_dl / LongitudinalLabResult.HB",
            rows=hb_rows,
            unit="g/dL",
            source_model="clinic.Assessment / twin_engine.LongitudinalLabResult",
            source_table="assessments / longitudinal_lab_results",
            source_fields=["hemoglobin_g_dl", "analyte=HB"],
            data_classification="raw_structured",
            used_by_model=True,
            used_in=["initialization", "toxicity_constraint", "backtesting"],
            why_it_matters="This helps describe blood reserve and is compared against predicted blood-related signals.",
            what_missing_means="Missing hemoglobin weakens blood-reserve interpretation and observed-vs-predicted comparison.",
            next_action_if_missing="Add structured hemoglobin rows.",
            detail_anchor="blood-marrow-details",
        ),
        _build_point(
            label="WBC",
            plain_name="White blood cell count",
            technical_field="LongitudinalLabResult.WBC",
            rows=wbc_rows,
            unit=_latest_unit(wbc_rows),
            source_model="twin_engine.LongitudinalLabResult",
            source_table="longitudinal_lab_results",
            source_fields=["analyte=WBC", "value", "unit"],
            data_classification="raw_structured",
            used_by_model=True,
            used_in=["toxicity_constraint"],
            why_it_matters="This helps describe background blood-cell reserve when blood-count interpretation is needed.",
            what_missing_means="Missing WBC leaves the page with a thinner view of blood reserve.",
            next_action_if_missing="Add structured WBC rows when available.",
            detail_anchor="blood-marrow-details",
        ),
        _build_point(
            label="NEU",
            plain_name="Neutrophil count",
            technical_field="LongitudinalLabResult.NEU",
            rows=neu_rows,
            unit=_latest_unit(neu_rows),
            source_model="twin_engine.LongitudinalLabResult",
            source_table="longitudinal_lab_results",
            source_fields=["analyte=NEU", "value", "unit"],
            data_classification="raw_structured",
            used_by_model=True,
            used_in=["toxicity_constraint"],
            why_it_matters="This supports neutropenia-related interpretation when structured rows are present.",
            what_missing_means="Missing neutrophil rows weaken toxicity interpretation for neutropenia-related vulnerability.",
            next_action_if_missing="Add structured neutrophil rows when available.",
            detail_anchor="blood-marrow-details",
        ),
        _build_point(
            label="PLT",
            plain_name="Platelet count",
            technical_field="LongitudinalLabResult.PLT",
            rows=plt_rows,
            unit=_latest_unit(plt_rows),
            source_model="twin_engine.LongitudinalLabResult",
            source_table="longitudinal_lab_results",
            source_fields=["analyte=PLT", "value", "unit"],
            data_classification="raw_structured",
            used_by_model=True,
            used_in=["toxicity_constraint"],
            why_it_matters="This adds blood-count context when marrow reserve is being reviewed.",
            what_missing_means="Missing platelet rows leave a gap in blood-reserve interpretation.",
            next_action_if_missing="Add structured platelet rows when available.",
            detail_anchor="blood-marrow-details",
        ),
    ]
    counts = {point["label"]: point["n_records"] for point in points}
    return _group(
        title="Blood / marrow markers",
        plain_explanation="These values help describe blood reserve and toxicity-related vulnerability.",
        data_source="Structured lab records and assessment records.",
        model_use="Used for initialization, toxicity context, and observed-vs-predicted comparison.",
        status=_status_from_counts(counts, enough_threshold=2),
        missingness_explanation=_field_count_message(
            counts,
            "Missing hemoglobin, WBC, NEU, or PLT weakens reserve and toxicity interpretation.",
        ),
        inspect_label="Inspect details",
        detail_anchor="blood-marrow-details",
        interpretation_risk="Missing blood counts weaken marrow-reserve and toxicity interpretation.",
        next_action_if_missing="Add structured blood-count rows.",
        data_points=points,
        source_rows=_latest_rows(_merge_rows(hb_rows, wbc_rows, neu_rows, plt_rows)),
        open_cockpit_href=cockpit_url + "#toxicity-constraints",
    )


def _build_liver_markers_group(patient: Patient, cockpit_url: str) -> dict[str, Any]:
    ast_rows = _lab_rows(patient, LongitudinalLabResult.ANALYTE_AST, meaning="Observed liver marker from structured lab row.")
    alt_rows = _lab_rows(patient, LongitudinalLabResult.ANALYTE_ALT, meaning="Observed liver marker from structured lab row.")
    steatosis_rows = _event_rows(patient, AdverseEvent.TYPE_HEPATIC_STEATOSIS, field_label="hepatic steatosis", meaning="Observed liver-related adverse event row.")
    hyper_rows = _event_rows(patient, AdverseEvent.TYPE_HYPERTRANSAMINASEMIA, field_label="hypertransaminasemia events", meaning="Observed liver-toxicity event row.")
    points = [
        _build_point(
            label="AST",
            plain_name="AST",
            technical_field="LongitudinalLabResult.AST",
            rows=ast_rows,
            unit=_latest_unit(ast_rows),
            source_model="twin_engine.LongitudinalLabResult",
            source_table="longitudinal_lab_results",
            source_fields=["analyte=AST", "value", "unit"],
            data_classification="raw_structured",
            used_by_model=True,
            used_in=["toxicity_constraint"],
            why_it_matters="AST helps anchor how liver-related treatment context is interpreted.",
            what_missing_means="Missing AST weakens the liver-toxicity interpretation layer.",
            next_action_if_missing="Add structured AST rows when available.",
            detail_anchor="liver-toxicity-details",
        ),
        _build_point(
            label="ALT",
            plain_name="ALT",
            technical_field="LongitudinalLabResult.ALT",
            rows=alt_rows,
            unit=_latest_unit(alt_rows),
            source_model="twin_engine.LongitudinalLabResult",
            source_table="longitudinal_lab_results",
            source_fields=["analyte=ALT", "value", "unit"],
            data_classification="raw_structured",
            used_by_model=True,
            used_in=["toxicity_constraint"],
            why_it_matters="ALT helps constrain how liver-related treatment history is interpreted.",
            what_missing_means="Missing ALT weakens liver-toxicity interpretation and makes prototype signals harder to anchor.",
            next_action_if_missing="Add structured ALT rows when available.",
            detail_anchor="liver-toxicity-details",
        ),
        _build_point(
            label="hepatic steatosis",
            plain_name="Hepatic steatosis event",
            technical_field="AdverseEvent.event_type=hepatic_steatosis",
            rows=steatosis_rows,
            unit="",
            source_model="twin_engine.AdverseEvent",
            source_table="adverse_events",
            source_fields=["event_type", "date", "grade", "action_taken"],
            data_classification="raw_structured",
            used_by_model=True,
            used_in=["toxicity_constraint"],
            why_it_matters="Observed liver-related events help interpret toxicity context.",
            what_missing_means="Missing liver-event rows mean the liver-toxicity story depends more heavily on lab values alone.",
            next_action_if_missing="Add structured liver-related adverse events when they exist.",
            detail_anchor="liver-toxicity-details",
        ),
        _build_point(
            label="hypertransaminasemia events",
            plain_name="Hypertransaminasemia events",
            technical_field="AdverseEvent.event_type=hypertransaminasemia",
            rows=hyper_rows,
            unit="",
            source_model="twin_engine.AdverseEvent",
            source_table="adverse_events",
            source_fields=["event_type", "date", "grade", "action_taken"],
            data_classification="raw_structured",
            used_by_model=True,
            used_in=["toxicity_constraint"],
            why_it_matters="These rows signal observed liver-toxicity context.",
            what_missing_means="Missing hypertransaminasemia rows weaken the liver-toxicity story even if AST/ALT exist.",
            next_action_if_missing="Add structured hypertransaminasemia event rows when available.",
            detail_anchor="liver-toxicity-details",
        ),
    ]
    counts = {point["label"]: point["n_records"] for point in points}
    return _group(
        title="Liver / toxicity markers",
        plain_explanation="These values constrain how treatment schedules are interpreted.",
        data_source="Structured lab records and adverse-event records.",
        model_use="Used for toxicity constraints and interpretation of toxicity-related outputs.",
        status=_status_from_counts(counts, enough_threshold=2),
        missingness_explanation=_field_count_message(
            counts,
            "Missing AST/ALT weakens toxicity interpretation. The toxicity layer remains a prototype research signal, not a validated AST/ALT prediction.",
        ),
        inspect_label="Inspect details",
        detail_anchor="liver-toxicity-details",
        interpretation_risk="Missing AST/ALT weakens toxicity interpretation.",
        next_action_if_missing="Add structured AST, ALT, or liver-event rows.",
        data_points=points,
        source_rows=_latest_rows(_merge_rows(ast_rows, alt_rows, steatosis_rows, hyper_rows)),
        open_cockpit_href=cockpit_url + "#toxicity-constraints",
    )


def _build_treatment_schedules_group(patient: Patient, cockpit_url: str) -> dict[str, Any]:
    therapies = list(patient.therapies.select_related("regimen").order_by("-start_date")[:10])
    raw_rows = _therapy_rows(therapies)
    points = [
        _build_point(
            label="Recorded treatment schedule",
            plain_name="Recorded treatment schedule",
            technical_field="PatientTherapy.regimen / doses / cycle_length_days / days_on / schedule_notes",
            rows=raw_rows,
            unit="",
            source_model="clinic.PatientTherapy",
            source_table="patient_therapy",
            source_fields=["regimen", "doses", "cycle_length_days", "days_on", "schedule_notes"],
            data_classification="raw_structured",
            used_by_model=True,
            used_in=["scenario_simulation", "backtesting"],
            why_it_matters="These are the dated therapy rows the model starts from when it reconstructs exposure history.",
            what_missing_means="Missing treatment schedule rows mean the page cannot explain real dose timing before simulation.",
            next_action_if_missing="Add or verify structured therapy rows.",
            detail_anchor="treatment-schedules-details",
        ),
        _build_point(
            label="Schedule-to-exposure summary",
            plain_name="Daily dose pattern used by the model",
            technical_field="therapy schedule -> daily exposure profile",
            rows=raw_rows,
            unit="",
            source_model="twin_engine exposure conversion",
            source_table="derived from patient_therapy",
            source_fields=["doses", "cycle_length_days", "days_on", "schedule_notes"],
            data_classification="derived",
            used_by_model=True,
            used_in=["scenario_simulation", "backtesting"],
            why_it_matters="The schedule-to-exposure step converts treatment timing into daily dose patterns for the model.",
            what_missing_means="If timing fields are missing, the model can still show that therapy existed, but the exposure pattern becomes weaker and less specific.",
            next_action_if_missing="Add cycle length, days-on, dose values, and schedule notes when available.",
            detail_anchor="treatment-schedules-details",
            value_summary=_derived_schedule_summary(therapies),
        ),
    ]
    return _group(
        title="Treatment schedules",
        plain_explanation="These are the dated therapy rows that become daily dose patterns.",
        data_source="Structured treatment course records.",
        model_use="Used for scenario simulation, exposure conversion, and background schedule interpretation.",
        status="enough" if therapies else "missing",
        missingness_explanation=_treatment_missingness(therapies),
        inspect_label="Inspect details",
        detail_anchor="treatment-schedules-details",
        interpretation_risk="Missing schedule timing weakens exposure interpretation.",
        next_action_if_missing="Add or verify therapy schedule rows.",
        data_points=points,
        source_rows=_latest_rows(raw_rows),
        open_cockpit_href=cockpit_url + "#what-if-scenarios",
    )


def _build_interruptions_group(patient: Patient, cockpit_url: str) -> dict[str, Any]:
    interruptions = list(patient.therapy_interruptions.order_by("-start_date")[:10])
    rows = _interruption_rows(interruptions)
    points = [
        _build_point(
            label="Recorded interruption rows",
            plain_name="Recorded treatment holds or pauses",
            technical_field="TherapyInterruption.start_date / end_date / drug / reason",
            rows=rows,
            unit="",
            source_model="twin_engine.TherapyInterruption",
            source_table="therapy_interruptions",
            source_fields=["start_date", "end_date", "drug", "reason", "action_taken"],
            data_classification="raw_structured",
            used_by_model=True,
            used_in=["toxicity_constraint"],
            why_it_matters="These rows tell the page whether treatment pauses or dose holds might explain part of the observed course.",
            what_missing_means="Missing interruption rows mean the schedule may look uninterrupted even if real pauses happened.",
            next_action_if_missing="Add structured interruption rows for treatment holds or pauses.",
            detail_anchor="interruptions-details",
        ),
    ]
    return _group(
        title="Interruptions",
        plain_explanation="These rows describe pauses, holds, or changes in exposure over time.",
        data_source="Structured interruption records.",
        model_use="Used in toxicity-constraint context and schedule interpretation.",
        status="enough" if interruptions else "missing",
        missingness_explanation="No interruption rows are recorded, so the page cannot show whether treatment pauses contributed to observed changes." if not interruptions else f"{len(interruptions)} interruption row{_plural_suffix(len(interruptions))} are available, so treatment holds can be inspected without raw JSON.",
        inspect_label="Inspect details",
        detail_anchor="interruptions-details",
        interpretation_risk="Missing interruption rows can hide treatment holds.",
        next_action_if_missing="Add structured interruption rows.",
        data_points=points,
        source_rows=_latest_rows(rows),
        open_cockpit_href=cockpit_url + "#toxicity-constraints",
    )


def _build_adverse_events_group(patient: Patient, cockpit_url: str) -> dict[str, Any]:
    events = list(patient.adverse_events.order_by("-date")[:10])
    rows = _adverse_event_rows(events)
    points = [
        _build_point(
            label="Recorded adverse events",
            plain_name="Observed adverse-event rows",
            technical_field="AdverseEvent.event_type / date / grade / action_taken",
            rows=rows,
            unit="",
            source_model="twin_engine.AdverseEvent",
            source_table="adverse_events",
            source_fields=["event_type", "date", "grade", "action_taken"],
            data_classification="raw_structured",
            used_by_model=True,
            used_in=["toxicity_constraint"],
            why_it_matters="Observed adverse events add real-world safety context to the toxicity story.",
            what_missing_means="Missing adverse-event rows weaken toxicity context and make the safety story narrower.",
            next_action_if_missing="Add or verify structured adverse-event rows.",
            detail_anchor="adverse-events-details",
        ),
    ]
    return _group(
        title="Adverse events",
        plain_explanation="These rows describe observed safety events that matter for interpretation.",
        data_source="Structured adverse-event records.",
        model_use="Used in toxicity-constraint context and safety interpretation.",
        status="enough" if events else "missing",
        missingness_explanation="No adverse-event rows are recorded, so the page cannot show structured safety-event context." if not events else f"{len(events)} adverse-event row{_plural_suffix(len(events))} are available for source-level inspection.",
        inspect_label="Inspect details",
        detail_anchor="adverse-events-details",
        interpretation_risk="Missing adverse-event rows weaken toxicity context.",
        next_action_if_missing="Add structured adverse-event rows.",
        data_points=points,
        source_rows=_latest_rows(rows),
        open_cockpit_href=cockpit_url + "#toxicity-constraints",
    )


def _build_twin_state_group(patient: Patient, current_state, cockpit_url: str) -> dict[str, Any]:
    states = list(patient.twin_states.order_by("-state_date", "-created_at")[:10])
    rows = _twin_state_rows(states)
    points = [
        _build_point(
            label="Current mathematical starting state",
            plain_name="Current mathematical starting state",
            technical_field="PatientTwinState.state_date / method / model_version / risk_score",
            rows=rows,
            unit="",
            source_model="twin_engine.PatientTwinState",
            source_table="twin_states",
            source_fields=["state_date", "method", "model_version", "risk_score"],
            data_classification="derived",
            used_by_model=True,
            used_in=["scenario_simulation", "uncertainty", "backtesting"],
            why_it_matters="This is the mathematical starting state used before running scenarios or diagnostics.",
            what_missing_means="Without a current mathematical starting state, the page cannot explain simulation outputs as patient-specific model branches.",
            next_action_if_missing="Initialize the mathematical starting state from the strongest available assessment.",
            detail_anchor="twin-state-details",
            value_summary=_twin_state_summary(current_state),
        ),
    ]
    status = "enough" if current_state else ("partial" if states else "missing")
    if current_state is None and patient.assessments.exists():
        missingness = "Assessments exist, but no current mathematical starting state has been created yet. Scenario simulation can exist only after that state is created."
    elif current_state is None:
        missingness = "No assessment exists, so no mathematical starting state can be derived yet."
    else:
        missingness = f"A current mathematical starting state exists for {current_state.state_date}. The page can explain where scenario simulation starts."
    return _group(
        title="Twin state",
        plain_explanation="This is the mathematical starting state used before running a simulation.",
        data_source="Derived research twin-state rows created from structured assessment data.",
        model_use="Used as the starting point for scenario simulation, uncertainty runs, and backtesting.",
        status=status,
        missingness_explanation=missingness,
        inspect_label="Inspect details",
        detail_anchor="twin-state-details",
        interpretation_risk="No mathematical starting state means scenario simulation cannot be interpreted.",
        next_action_if_missing="Create or review the mathematical starting state.",
        data_points=points,
        source_rows=_latest_rows(rows),
        open_cockpit_href=cockpit_url + "#twin-state",
    )


def _build_calibration_group(patient: Patient, current_state, validation_panel: dict[str, Any], cockpit_url: str) -> dict[str, Any]:
    residuals = list(patient.observation_residuals.select_related("assessment").order_by("-created_at")[:10])
    residual_rows = _residual_rows(residuals)
    backtest_metadata = None
    if current_state is not None:
        backtest_metadata = SimulationRunMetadata.objects.filter(
            twin_state=current_state,
            solver_name="rolling_origin_backtest",
        ).order_by("-created_at").first()
    backtest_rows = _backtest_rows(backtest_metadata, (validation_panel.get("backtest") or {}).get("summary") or {})
    points = [
        _build_point(
            label="Observed-versus-predicted residual summary",
            plain_name="Observed-versus-predicted mismatch summary",
            technical_field="ObservationResidual.rmse / mae / stage",
            rows=residual_rows,
            unit="",
            source_model="twin_engine.ObservationResidual",
            source_table="observation_residuals",
            source_fields=["rmse", "mae", "stage", "assessment"],
            data_classification="derived",
            used_by_model=True,
            used_in=["calibration"],
            why_it_matters="These rows show how closely recorded observations and model predictions line up after calibration work.",
            what_missing_means="No residual rows means calibration fit is not yet inspectable from structured records.",
            next_action_if_missing="Run or review calibration before trusting scenario fit.",
            detail_anchor="calibration-details",
            value_summary=_residual_summary(residuals),
        ),
        _build_point(
            label="Rolling backtest summary",
            plain_name="Held-out fit check",
            technical_field="SimulationRunMetadata.solver_parameters.diagnostic_summary",
            rows=backtest_rows,
            unit="",
            source_model="twin_engine.SimulationRunMetadata",
            source_table="simulation_run_metadata",
            source_fields=["solver_name", "solver_parameters.diagnostic_summary"],
            data_classification="derived",
            used_by_model=True,
            used_in=["backtesting"],
            why_it_matters="This shows whether held-out recorded biomarker points agree with the fitted model.",
            what_missing_means="No backtest means predictive reliability is unknown for held-out points.",
            next_action_if_missing="Run the rolling backtest before making stronger claims about predictive reliability.",
            detail_anchor="calibration-details",
            value_summary=_backtest_value_summary((validation_panel.get("backtest") or {}).get("summary") or {}),
        ),
    ]
    status = "enough" if residuals or backtest_rows else ("partial" if current_state else "missing")
    if residuals or backtest_rows:
        missingness = "Calibration evidence is available from residual rows or a stored backtest summary, so fit quality can be explained without raw JSON."
    elif current_state is not None:
        missingness = "A mathematical starting state exists, but there are no residual rows or backtest summary yet. Predictive reliability is still unknown."
    else:
        missingness = "No current mathematical starting state exists, so calibration evidence cannot be generated yet."
    return _group(
        title="Calibration",
        plain_explanation="These values describe how closely observed and predicted markers agree.",
        data_source="Residual records and stored rolling-backtest summaries.",
        model_use="Used for calibration review and backtesting, not as a direct clinical output.",
        status=status,
        missingness_explanation=missingness,
        inspect_label="Inspect details",
        detail_anchor="calibration-details",
        interpretation_risk="No backtest means predictive reliability is unknown.",
        next_action_if_missing="Run or review calibration and backtesting.",
        data_points=points,
        source_rows=_latest_rows(_merge_rows(residual_rows, backtest_rows)),
        open_cockpit_href=cockpit_url + "#validation-and-uncertainty",
    )


def _build_simulated_scenarios_group(patient: Patient, scenario_rows: list[dict[str, Any]], cockpit_url: str) -> dict[str, Any]:
    rows = _scenario_source_rows(scenario_rows)
    points = [
        _build_point(
            label="Predicted scenario outputs",
            plain_name="Predicted scenario outputs",
            technical_field="CounterfactualRun.simulation_summary / comparison_metrics",
            rows=rows,
            unit="",
            source_model="twin_engine.CounterfactualRun",
            source_table="counterfactual_runs",
            source_fields=["simulation_summary", "comparison_metrics", "created_at"],
            data_classification="simulated",
            used_by_model=False,
            used_in=["scenario_simulation"],
            why_it_matters="These are the model-generated outputs that let the page compare alternative schedules.",
            what_missing_means="No simulated scenarios means the page cannot compare alternative schedules yet.",
            next_action_if_missing="Run completed scenario simulations.",
            detail_anchor="simulated-scenarios-details",
            value_summary=_scenario_value_summary(scenario_rows),
        ),
        _build_point(
            label="Heuristic research score",
            plain_name="Heuristic research score",
            technical_field="comparison_metrics.research_utility_v2",
            rows=rows,
            unit="",
            source_model="twin_engine.CounterfactualRun",
            source_table="counterfactual_runs",
            source_fields=["comparison_metrics.research_utility_v2"],
            data_classification="heuristic",
            used_by_model=False,
            used_in=["display_only"],
            why_it_matters="This is the heuristic research score called utility_v2. It helps rank model branches during research review.",
            what_missing_means="If the heuristic score is missing, scenario comparison can still exist, but ranking becomes thinner.",
            next_action_if_missing="Open the scientific cockpit to inspect scenario-level technical details.",
            detail_anchor="simulated-scenarios-details",
            value_summary=_scenario_utility_summary(scenario_rows),
        ),
    ]
    return _group(
        title="Simulated scenarios",
        plain_explanation="These are model-generated trajectories and summaries under alternative schedules.",
        data_source="Completed scenario runs and report summaries.",
        model_use="Generated by scenario simulation for comparison only; not reused as a patient input unless a new run is created.",
        status="enough" if scenario_rows else "missing",
        missingness_explanation="Completed scenarios are available, so the page can explain schedule differences without raw JSON." if scenario_rows else "No completed scenario runs exist, so schedule comparison is unavailable.",
        inspect_label="Inspect details",
        detail_anchor="simulated-scenarios-details",
        interpretation_risk="No scenario outputs means schedule comparison is unavailable.",
        next_action_if_missing="Run scenario simulations.",
        data_points=points,
        source_rows=_latest_rows(rows),
        open_cockpit_href=cockpit_url + "#what-if-scenarios",
    )


def _build_uncertainty_group(
    patient: Patient,
    scenario_rows: list[dict[str, Any]],
    validation_panel: dict[str, Any],
    cockpit_url: str,
) -> dict[str, Any]:
    rows = _uncertainty_source_rows(scenario_rows, validation_panel)
    uncertainty_rows = validation_panel.get("uncertainty_rows") or []
    robustness_summary = (validation_panel.get("robustness") or {}).get("summary") or {}
    points = [
        _build_point(
            label="Stored uncertainty range",
            plain_name="Stored uncertainty range",
            technical_field="SimulationRunMetadata.solver_parameters.diagnostic_summary.metric_summaries",
            rows=rows,
            unit="",
            source_model="twin_engine.SimulationRunMetadata",
            source_table="simulation_run_metadata",
            source_fields=["solver_name", "solver_parameters.diagnostic_summary"],
            data_classification="heuristic",
            used_by_model=False,
            used_in=["uncertainty"],
            why_it_matters="This shows how much a stored output moves under the current perturbation checks.",
            what_missing_means="No stored uncertainty range means ranking stability cannot be explained yet.",
            next_action_if_missing="Run scenario uncertainty diagnostics.",
            detail_anchor="uncertainty-robustness-details",
            value_summary=_uncertainty_value_summary(uncertainty_rows),
        ),
        _build_point(
            label="Ranking stability summary",
            plain_name="Ranking stability summary",
            technical_field="robust_scenario_ranking rows",
            rows=rows,
            unit="",
            source_model="twin_engine.SimulationRunMetadata",
            source_table="simulation_run_metadata",
            source_fields=["solver_name", "solver_parameters.diagnostic_summary.rows"],
            data_classification="heuristic",
            used_by_model=False,
            used_in=["robustness"],
            why_it_matters="This shows whether a scenario rank remains stable or fragile under the stored uncertainty checks.",
            what_missing_means="Without ranking-stability rows, the page cannot say whether a top scenario is robust or fragile.",
            next_action_if_missing="Run the robust ranking diagnostic.",
            detail_anchor="uncertainty-robustness-details",
            value_summary=_robustness_value_summary(robustness_summary),
        ),
    ]
    status = "enough" if rows else ("partial" if scenario_rows else "missing")
    if rows:
        missingness = "Stored uncertainty and ranking-stability diagnostics are available, so the page can explain whether scenario outputs look stable or fragile."
    elif scenario_rows:
        missingness = "Scenarios exist, but uncertainty or ranking-stability diagnostics are still missing. Ranking stability is unknown."
    else:
        missingness = "No scenarios exist yet, so uncertainty and ranking-stability diagnostics cannot be shown."
    return _group(
        title="Uncertainty / robustness",
        plain_explanation="These are research diagnostics showing how stable outputs and rankings remain under stored perturbation checks.",
        data_source="Scenario uncertainty summaries and patient-level robust ranking summaries.",
        model_use="Used for uncertainty review and ranking stability checks; not a clinical confidence statement.",
        status=status,
        missingness_explanation=missingness,
        inspect_label="Inspect details",
        detail_anchor="uncertainty-robustness-details",
        interpretation_risk="Wide uncertainty means scenario ranking is unstable.",
        next_action_if_missing="Run or review uncertainty and ranking-stability diagnostics.",
        data_points=points,
        source_rows=_latest_rows(rows),
        open_cockpit_href=cockpit_url + "#validation-and-uncertainty",
    )


def _build_model_input_map(groups: list[dict[str, Any]]) -> list[dict[str, str]]:
    return [
        {
            "input_group": group["title"],
            "used_fields": ", ".join(point["label"] for point in group["data_points"]),
            "model_role": group["model_use"],
            "available": "Yes" if group["status"] != "missing" else "No",
            "missing": group["missingness_explanation"],
            "interpretation_risk": group["interpretation_risk"],
        }
        for group in groups
    ]


def _build_scenario_explanations(
    scenario_rows: list[dict[str, Any]],
    validation_panel: dict[str, Any],
) -> dict[str, dict[str, Any]]:
    robustness_rows = {
        row.get("scenario_label"): row
        for row in (((validation_panel.get("robustness") or {}).get("summary") or {}).get("rows") or [])
    }
    explanations: dict[str, dict[str, Any]] = {}
    for row in scenario_rows:
        utility_summary = ((row.get("uncertainty") or {}).get("metric_summaries") or {}).get("research_utility_v2") or {}
        robustness_row = robustness_rows.get(row["label"]) or {}
        explanations[row["label"]] = {
            "why_result_points": [
                _why_point(
                    label="Schedule exposure pattern",
                    detail=_schedule_explanation(row),
                    data_classification="derived",
                ),
                _why_point(
                    label="What model changed",
                    detail="The run keeps the same mathematical starting state but changes the intervention schedule, so the simulated trajectory is driven by a different daily exposure pattern.",
                    data_classification="simulated",
                ),
                _why_point(
                    label="What output changed",
                    detail=_output_change_explanation(row),
                    data_classification="simulated",
                ),
                _why_point(
                    label="What toxicity signal changed",
                    detail=_toxicity_change_explanation(row),
                    data_classification="heuristic",
                ),
                _why_point(
                    label="Uncertainty / robustness status",
                    detail=_uncertainty_robustness_explanation(utility_summary, robustness_row),
                    data_classification="heuristic" if utility_summary or robustness_row else "missing",
                ),
            ],
            "exposure_classification_label": CLASSIFICATION_LABELS["derived"],
            "disease_signal_classification_label": CLASSIFICATION_LABELS["simulated"],
            "healthy_signal_classification_label": CLASSIFICATION_LABELS["simulated"],
            "toxicity_signal_classification_label": CLASSIFICATION_LABELS["heuristic"],
            "uncertainty_signal_classification_label": CLASSIFICATION_LABELS["heuristic"] if utility_summary else CLASSIFICATION_LABELS["missing"],
        }
    return explanations


def _group(
    *,
    title: str,
    plain_explanation: str,
    data_source: str,
    model_use: str,
    status: str,
    missingness_explanation: str,
    inspect_label: str,
    detail_anchor: str,
    interpretation_risk: str,
    next_action_if_missing: str,
    data_points: list[dict[str, Any]],
    source_rows: list[dict[str, Any]],
    open_cockpit_href: str,
) -> dict[str, Any]:
    return {
        "title": title,
        "plain_explanation": plain_explanation,
        "data_source": data_source,
        "model_use": model_use,
        "status": status,
        "status_label": status,
        "missingness_explanation": missingness_explanation,
        "inspect_label": inspect_label,
        "detail_anchor": detail_anchor,
        "interpretation_risk": interpretation_risk,
        "next_action_if_missing": next_action_if_missing,
        "data_points": data_points,
        "source_rows": source_rows,
        "source_rows_available": bool(source_rows),
        "open_cockpit_href": open_cockpit_href,
    }


def _build_point(
    *,
    label: str,
    plain_name: str,
    technical_field: str,
    rows: list[dict[str, Any]],
    unit: str,
    source_model: str,
    source_table: str,
    source_fields: list[str],
    data_classification: str,
    used_by_model: bool,
    used_in: list[str],
    why_it_matters: str,
    what_missing_means: str,
    next_action_if_missing: str,
    detail_anchor: str,
    value_summary: str | None = None,
) -> dict[str, Any]:
    classification = data_classification if rows else "missing"
    return DataPointExplanation(
        label=label,
        plain_name=plain_name,
        technical_field=technical_field,
        value_summary=value_summary or _default_value_summary(rows, unit),
        unit=unit,
        date_range=_date_range_from_rows(rows),
        n_records=len(rows),
        source_model=source_model,
        source_table=source_table,
        source_fields=source_fields,
        data_classification=classification,
        used_by_model=used_by_model,
        used_in=used_in,
        why_it_matters=why_it_matters,
        what_missing_means=what_missing_means,
        next_action_if_missing=next_action_if_missing,
        source_rows_available=bool(rows),
        detail_anchor=detail_anchor,
    ).as_dict()


def _assessment_rows(patient: Patient, field_name: str, *, label: str, meaning: str) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    unit = ASSESSMENT_FIELD_UNITS.get(field_name, "")
    for assessment in patient.assessments.order_by("-date"):
        value = getattr(assessment, field_name, None)
        if value is None:
            continue
        rows.append(
            _row(
                date_obj=assessment.date,
                field=label,
                value=_format_scalar(value),
                unit=unit,
                source_type="Assessment record",
                used_by_model=True,
                meaning=meaning,
                data_classification="raw_structured",
            )
        )
    return rows


def _lab_rows(patient: Patient, analyte: str, *, meaning: str) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    analyte_label = dict(LongitudinalLabResult.ANALYTE_CHOICES).get(analyte, analyte)
    for result in patient.longitudinal_lab_results.filter(analyte=analyte).order_by("-date", "-created_at"):
        if result.value is None:
            continue
        rows.append(
            _row(
                date_obj=result.date,
                field=analyte_label,
                value=_format_scalar(result.value),
                unit=result.unit or "",
                source_type=result.get_source_quality_display(),
                used_by_model=True,
                meaning=meaning,
                data_classification="raw_structured",
            )
        )
    return rows


def _event_rows(patient: Patient, event_type: str, *, field_label: str, meaning: str) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for event in patient.adverse_events.filter(event_type=event_type).order_by("-date", "-created_at"):
        value = field_label
        if event.grade:
            value = f"{field_label}; grade {event.grade}"
        rows.append(
            _row(
                date_obj=event.date,
                field=field_label,
                value=value,
                unit="",
                source_type="Adverse event record",
                used_by_model=True,
                meaning=meaning,
                data_classification="raw_structured",
            )
        )
    return rows


def _therapy_rows(therapies: list[PatientTherapy]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for therapy in therapies:
        rows.append(
            _row(
                date_obj=therapy.start_date,
                field="Treatment schedule",
                value=f"{therapy.regimen.name}; {_format_therapy_value(therapy)}",
                unit="",
                source_type=therapy.get_source_quality_display(),
                used_by_model=True,
                meaning="Recorded therapy row used to build the daily exposure pattern.",
                data_classification="raw_structured",
            )
        )
    return rows


def _interruption_rows(interruptions: list[TherapyInterruption]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for interruption in interruptions:
        value = interruption.reason.replace("_", " ")
        if interruption.end_date:
            value = f"{value}; through {interruption.end_date.isoformat()}"
        rows.append(
            _row(
                date_obj=interruption.start_date,
                field=interruption.drug,
                value=value,
                unit="",
                source_type=interruption.source_quality.replace("_", " "),
                used_by_model=True,
                meaning="Structured interruption row used to explain treatment holds or pauses.",
                data_classification="raw_structured",
            )
        )
    return rows


def _adverse_event_rows(events: list[AdverseEvent]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for event in events:
        value = event.get_event_type_display()
        if event.grade:
            value = f"{value}; grade {event.grade}"
        rows.append(
            _row(
                date_obj=event.date,
                field=event.get_event_type_display(),
                value=value,
                unit="",
                source_type="Adverse event record",
                used_by_model=True,
                meaning="Observed safety-event row used for toxicity context.",
                data_classification="raw_structured",
            )
        )
    return rows


def _twin_state_rows(states: list[PatientTwinState]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for state in states:
        rows.append(
            _row(
                date_obj=state.state_date,
                field="Mathematical starting state",
                value=f"{state.get_method_display()}; model {state.model_version}; risk score {_format_scalar(state.risk_score)}",
                unit="",
                source_type="Derived twin-state row",
                used_by_model=True,
                meaning="Derived model state used as the starting point for simulation.",
                data_classification="derived",
            )
        )
    return rows


def _residual_rows(residuals: list[ObservationResidual]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for residual in residuals:
        date_obj = residual.assessment.date if residual.assessment else residual.created_at.date()
        rows.append(
            _row(
                date_obj=date_obj,
                field="Observed-versus-predicted mismatch",
                value=f"average mismatch {_format_scalar(residual.rmse)}; absolute mismatch {_format_scalar(residual.mae)}",
                unit="",
                source_type="Derived residual record",
                used_by_model=True,
                meaning="Derived fit-diagnostic row showing how observed and predicted values differ.",
                data_classification="derived",
            )
        )
    return rows


def _backtest_rows(metadata: SimulationRunMetadata | None, summary: dict[str, Any]) -> list[dict[str, Any]]:
    if metadata is None or not summary:
        return []
    return [
        _row(
            date_obj=metadata.created_at.date(),
            field="Held-out fit check",
            value=f"{summary.get('n_folds', 0)} folds; overall mismatch {_format_scalar(summary.get('overall_rmse'))}",
            unit="",
            source_type="Derived backtest summary",
            used_by_model=True,
            meaning="Derived held-out fit summary used to describe predictive reliability.",
            data_classification="derived",
        )
    ]


def _scenario_source_rows(scenario_rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for row in scenario_rows[:10]:
        rows.append(
            _row(
                date_obj=row["run"].created_at.date(),
                field=row["label"],
                value=f"utility_v2 {_format_scalar(row.get('utility_v2'))}; disease signal {row.get('tumor_reduction_delta') if row.get('tumor_reduction_delta') is not None else 'n/a'}",
                unit="",
                source_type="Simulated scenario row",
                used_by_model=False,
                meaning="Model-generated scenario output summary.",
                data_classification="simulated",
            )
        )
    return rows


def _uncertainty_source_rows(scenario_rows: list[dict[str, Any]], validation_panel: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    uncertainty_by_label = {
        row.get("label"): row
        for row in (validation_panel.get("uncertainty_rows") or [])
    }
    robustness_rows = {
        row.get("scenario_label"): row
        for row in (((validation_panel.get("robustness") or {}).get("summary") or {}).get("rows") or [])
    }
    for scenario in scenario_rows[:10]:
        uncertainty_row = uncertainty_by_label.get(scenario["label"]) or {}
        utility_summary = uncertainty_row.get("research_utility_v2") or {}
        robustness_row = robustness_rows.get(scenario["label"]) or {}
        if utility_summary:
            rows.append(
                _row(
                    date_obj=scenario["run"].created_at.date(),
                    field=f"{scenario['label']} uncertainty",
                    value=f"{utility_summary.get('uncertainty_classification', 'unknown')} around {_format_scalar(utility_summary.get('median'))}",
                    unit="",
                    source_type="Heuristic uncertainty summary",
                    used_by_model=False,
                    meaning="Stored perturbation-based output range.",
                    data_classification="heuristic",
                )
            )
        if robustness_row:
            rows.append(
                _row(
                    date_obj=scenario["run"].created_at.date(),
                    field=f"{scenario['label']} ranking stability",
                    value=f"rank {robustness_row.get('robust_rank')}; {robustness_row.get('robustness_classification', 'unknown')}",
                    unit="",
                    source_type="Heuristic ranking-stability summary",
                    used_by_model=False,
                    meaning="Stored robust-ranking summary.",
                    data_classification="heuristic",
                )
            )
    return rows


def _row(
    *,
    date_obj: date,
    field: str,
    value: str,
    unit: str,
    source_type: str,
    used_by_model: bool,
    meaning: str,
    data_classification: str,
) -> dict[str, Any]:
    return {
        "sort_date": date_obj,
        "date": date_obj.isoformat(),
        "field": field,
        "value": value,
        "unit": unit or "-",
        "source_type": source_type,
        "used_by_model": used_by_model,
        "used_by_model_label": "Yes" if used_by_model else "No",
        "meaning": meaning,
        "data_classification": data_classification,
        "data_classification_label": CLASSIFICATION_LABELS[data_classification],
    }


def _why_point(*, label: str, detail: str, data_classification: str) -> dict[str, str]:
    return {
        "label": label,
        "detail": detail,
        "data_classification": data_classification,
        "data_classification_label": CLASSIFICATION_LABELS[data_classification],
    }


def _merge_rows(*groups: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    rows = [row for group in groups for row in group]
    return sorted(rows, key=lambda item: (item["sort_date"], item["field"]), reverse=True)


def _latest_rows(rows: list[dict[str, Any]], *, limit: int = 10) -> list[dict[str, Any]]:
    trimmed = sorted(rows, key=lambda item: (item["sort_date"], item["field"]), reverse=True)[:limit]
    result = []
    for row in trimmed:
        copied = dict(row)
        copied.pop("sort_date", None)
        result.append(copied)
    return result


def _status_from_counts(counts: dict[str, int], *, enough_threshold: int) -> str:
    present = sum(1 for count in counts.values() if count > 0)
    if present >= enough_threshold:
        return "enough"
    if present > 0:
        return "partial"
    return "missing"


def _field_count_message(counts: dict[str, int], impact: str) -> str:
    available = [f"{label} is available on {count} row{_plural_suffix(count)}" for label, count in counts.items() if count > 0]
    missing = [label for label, count in counts.items() if count == 0]
    parts = []
    if available:
        parts.append("; ".join(available[:4]))
    else:
        parts.append("No structured rows are available for this block")
    if missing:
        parts.append(f"Missing now: {', '.join(missing)}")
    parts.append(impact)
    return ". ".join(part.strip(".") for part in parts if part) + "."


def _treatment_missingness(therapies: list[PatientTherapy]) -> str:
    if not therapies:
        return "No treatment schedule rows are recorded, so the page cannot explain dose timing or the schedule-to-exposure step."
    schedule_notes = sum(1 for therapy in therapies if therapy.schedule_notes)
    cycle_lengths = sum(1 for therapy in therapies if therapy.cycle_length_days)
    days_on = sum(1 for therapy in therapies if therapy.days_on)
    return (
        f"{len(therapies)} treatment row{_plural_suffix(len(therapies))} are available. "
        f"Schedule notes exist on {schedule_notes} row{_plural_suffix(schedule_notes)}, cycle length on {cycle_lengths}, and days-on on {days_on}. "
        "If timing fields are missing, the page can still show that therapy existed, but the exposure pattern becomes weaker and less specific."
    )


def _default_value_summary(rows: list[dict[str, Any]], unit: str) -> str:
    if not rows:
        return "Not available in structured form."
    latest = rows[0]
    value = latest["value"]
    unit_text = f" {unit}" if unit and unit != "-" else ""
    return f"Latest {value}{unit_text}; {len(rows)} structured row{_plural_suffix(len(rows))}."


def _date_range_from_rows(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return "No dated rows"
    values = sorted({row["sort_date"] for row in rows})
    if len(values) == 1:
        return values[0].isoformat()
    return f"{values[0].isoformat()} to {values[-1].isoformat()}"


def _latest_unit(rows: list[dict[str, Any]]) -> str:
    return rows[0]["unit"] if rows else ""


def _format_scalar(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, str):
        return value
    if isinstance(value, Decimal):
        value = float(value)
    if isinstance(value, float):
        return f"{value:.3f}".rstrip("0").rstrip(".")
    return str(value)


def _format_therapy_value(therapy: PatientTherapy) -> str:
    doses = []
    for drug, dose in sorted((therapy.doses or {}).items()):
        dose_text = _format_scalar(dose)
        doses.append(f"{drug} {dose_text} mg")
    bits = [", ".join(doses) if doses else "dose not structured"]
    if therapy.cycle_length_days:
        bits.append(f"cycle {therapy.cycle_length_days} days")
    if therapy.days_on:
        bits.append(f"days on {', '.join(str(item) for item in therapy.days_on[:8])}")
    if therapy.schedule_notes:
        bits.append(therapy.schedule_notes)
    return "; ".join(bits)


def _derived_schedule_summary(therapies: list[PatientTherapy]) -> str:
    if not therapies:
        return "No structured schedule exists, so no daily exposure pattern can be derived."
    with_timing = sum(1 for therapy in therapies if therapy.cycle_length_days or therapy.days_on or therapy.schedule_notes)
    return (
        f"The schedule-to-exposure step can derive daily dose patterns from {with_timing} treatment row{_plural_suffix(with_timing)} "
        f"out of {len(therapies)} recorded treatment row{_plural_suffix(len(therapies))}."
    )


def _twin_state_summary(current_state) -> str:
    if current_state is None:
        return "No current mathematical starting state is available."
    return (
        f"Current state on {current_state.state_date.isoformat()} using {current_state.get_method_display()} "
        f"with model version {current_state.model_version}."
    )


def _residual_summary(residuals: list[ObservationResidual]) -> str:
    if not residuals:
        return "No residual summary is stored."
    latest = residuals[0]
    return f"Latest average mismatch {_format_scalar(latest.rmse)} and absolute mismatch {_format_scalar(latest.mae)}."


def _backtest_value_summary(summary: dict[str, Any]) -> str:
    if not summary:
        return "No held-out fit summary is stored."
    return (
        f"{summary.get('n_folds', 0)} held-out fold{_plural_suffix(summary.get('n_folds', 0))}; "
        f"overall mismatch {_format_scalar(summary.get('overall_rmse'))}."
    )


def _scenario_value_summary(scenario_rows: list[dict[str, Any]]) -> str:
    if not scenario_rows:
        return "No completed scenario outputs are stored."
    return f"{len(scenario_rows)} completed scenario row{_plural_suffix(len(scenario_rows))} are available for comparison."


def _scenario_utility_summary(scenario_rows: list[dict[str, Any]]) -> str:
    if not scenario_rows:
        return "No heuristic research score is stored because no scenario is available."
    values = [row.get("utility_v2") for row in scenario_rows if row.get("utility_v2") is not None]
    if not values:
        return "Scenario outputs exist, but the heuristic research score is missing."
    return f"Heuristic research score available on {len(values)} scenario row{_plural_suffix(len(values))}; latest {_format_scalar(values[0])}."


def _uncertainty_value_summary(uncertainty_rows: list[dict[str, Any]]) -> str:
    if not uncertainty_rows:
        return "No stored uncertainty range is available."
    classifications = [
        row.get("research_utility_v2", {}).get("uncertainty_classification")
        for row in uncertainty_rows
        if row.get("research_utility_v2")
    ]
    classifications = [value for value in classifications if value]
    if not classifications:
        return "Uncertainty rows exist, but the utility range classification is unavailable."
    return f"Stored uncertainty classifications: {', '.join(sorted(set(classifications)))}."


def _robustness_value_summary(robustness_summary: dict[str, Any]) -> str:
    rows = robustness_summary.get("rows") or []
    if not rows:
        return "No ranking-stability summary is stored."
    top = rows[0]
    return (
        f"Top stored rank is {top.get('scenario_label', 'unknown')} with robust rank {top.get('robust_rank', 'n/a')} "
        f"and status {top.get('robustness_classification', 'unknown')}."
    )


def _schedule_explanation(row: dict[str, Any]) -> str:
    average = row.get("average_daily_exposure_mg")
    peak = row.get("peak_daily_dose_mg")
    temporal_profile = row.get("temporal_profile") or "unavailable"
    if average is None and peak is None:
        return "The schedule-to-exposure step could not summarize the stored schedule timing for this run."
    return (
        f"The schedule-to-exposure step converts treatment timing into a daily pattern with roughly {_format_scalar(average)} mg/day average exposure "
        f"and {_format_scalar(peak)} mg peak exposure; temporal profile is {temporal_profile}."
    )


def _output_change_explanation(row: dict[str, Any]) -> str:
    tumor = row.get("tumor_reduction_delta")
    healthy = row.get("healthy_loss_delta")
    return (
        f"The disease-control signal changes by {_format_scalar(tumor)} while healthy-tissue strain changes by {_format_scalar(healthy)} relative to the stored baseline comparison."
    )


def _toxicity_change_explanation(row: dict[str, Any]) -> str:
    liver = row.get("liver_signal")
    neutropenia = row.get("neutropenia_signal")
    if liver is None and neutropenia is None:
        return "No stored prototype toxicity signal is available for this scenario."
    return (
        f"The prototype liver signal is {_format_scalar(liver)} and the prototype neutropenia signal is {_format_scalar(neutropenia)}; both remain research-only normalized signals."
    )


def _uncertainty_robustness_explanation(utility_summary: dict[str, Any], robustness_row: dict[str, Any]) -> str:
    parts = []
    if utility_summary:
        parts.append(
            f"Stored uncertainty range is {utility_summary.get('uncertainty_classification', 'unknown')} around median {_format_scalar(utility_summary.get('median'))}"
        )
    if robustness_row:
        parts.append(
            f"ranking stability is {robustness_row.get('robustness_classification', 'unknown')} at robust rank {robustness_row.get('robust_rank', 'n/a')}"
        )
    if not parts:
        return "No stored uncertainty or ranking-stability summary is available."
    return "; ".join(parts) + "."


def _plural_suffix(value: int) -> str:
    return "s" if value != 1 else ""
