# Generated by Django 4.2.25 on 2025-10-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PARAM', 'Drug Parameters'), ('BIND', 'Binding Visualizer'), ('SIM', 'Similarity Search')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('input_a', models.CharField(blank=True, max_length=255)),
                ('input_b', models.CharField(blank=True, max_length=255)),
                ('out_html', models.FileField(blank=True, null=True, upload_to='chem/html/')),
                ('out_csv', models.FileField(blank=True, null=True, upload_to='chem/csv/')),
                ('log', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
