# Generated by Django 4.2.25 on 2025-11-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemtools', '0002_chemjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemjob',
            name='progress_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chemjob',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
    ]
