from __future__ import annotations

import shutil
import tempfile
from pathlib import Path

from celery import shared_task
from django.conf import settings
import traceback

from . import models, utils


def _compose_log(stdout: str, stderr: str) -> str:
    parts = []
    if stdout:
        parts.append(stdout)
    if stderr:
        parts.append("--- STDERR ---")
        parts.append(stderr)
    if parts:
        return "\n".join(parts)
    return "(no output captured)"


def _job_media_dir(job_id: int) -> Path:
    base = Path(settings.MEDIA_ROOT) / "chem" / str(job_id)
    base.mkdir(parents=True, exist_ok=True)
    return base


def _store_file(src: Path, dest: Path) -> str:
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists():
        dest.unlink()
    shutil.move(str(src), str(dest))
    relative = dest.relative_to(Path(settings.MEDIA_ROOT)).as_posix()
    return relative


def _ensure_placeholder_thumbnail(dest: Path) -> None:
    if dest.exists():
        return
    placeholder = (
        b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x08\x00\x00\x00\x08\x08\x06\x00\x00\x00\xc4\x0f\xbe\x8b"
        b"\x00\x00\x00\x06bKGD\x00\xff\x00\xff\x00\xff\xa0\xbd\xa7\x93\x00\x00\x00\x19tEXtSoftware\x00Generated by MM Portal\x00\x00\x00uIDATX\xc3c`\x18\x05\xa3`\x14\x8c\x02\x00\x07\x18\x02\x17\xc3\x8d\x9c<\x00\x00\x00\x00IEND\xaeB`\x82"
    )
    dest.write_bytes(placeholder)


@shared_task
def run_drug_params_job(job_id: int, smiles: str, cid: str) -> None:
    job = models.ChemJob.objects.get(pk=job_id)
    tmpdir = Path(tempfile.mkdtemp(prefix="chem_drug_"))
    previous_log = job.log or ""
    try:
        utils.run_settings_generator()
        utils.run_paths_generator()
        output_path, stdout, stderr = utils.run_drug_parameter_evaluator(
            smiles=smiles or None,
            cid=cid or None,
            outdir=tmpdir,
        )
        new_log = _compose_log(stdout, stderr)
        job.log = (previous_log + "\n---\n" + new_log).strip() if previous_log else new_log
        if output_path and output_path.is_file():
            job_dir = _job_media_dir(job.pk)
            version = len(list(job_dir.glob("drug_*.html"))) + 1
            filename = f"drug_{job.pk}.html" if version == 1 else f"drug_{job.pk}_v{version}.html"
            dest = job_dir / filename
            job.out_html.name = _store_file(output_path, dest)
    except Exception as exc:  # pragma: no cover - defensive
        error_entry = f"ERROR: {exc}"
        job.log = (previous_log + "\n---\n" + error_entry).strip() if previous_log else error_entry
    finally:
        job.save()
        shutil.rmtree(tmpdir, ignore_errors=True)


@shared_task
def run_binding_viz_job(job_id: int, pdb_id: str, ligand: str) -> None:
    job = models.ChemJob.objects.get(pk=job_id)
    tmpdir = Path(tempfile.mkdtemp(prefix="chem_bind_"))
    stdout = ""
    stderr = ""
    previous_log = job.log or ""
    try:
        utils.run_settings_generator()
        utils.run_paths_generator()
        output_path, stdout, stderr = utils.run_binding_visualizer(
            pdb_id=pdb_id,
            ligand=ligand or None,
            outdir=tmpdir,
        )
        new_log = _compose_log(stdout, stderr)
        job.log = (previous_log + "\n---\n" + new_log).strip() if previous_log else new_log
        job_dir = _job_media_dir(job.pk)
        if output_path and output_path.is_file():
            version = len(list(job_dir.glob("binding_*.html"))) + 1
            base_name = f"binding_{pdb_id}.html" if version == 1 else f"binding_{pdb_id}_v{version}.html"
            dest = job_dir / base_name
            job.out_html.name = _store_file(output_path, dest)

        snapshot_path = tmpdir / f"{pdb_id}_structure.png"
        thumb_dest = job_dir / "thumb.png"
        if snapshot_path.exists():
            _store_file(snapshot_path, thumb_dest)
        else:
            _ensure_placeholder_thumbnail(thumb_dest)
    except Exception as exc:  # pragma: no cover
        error_log = _compose_log(stdout, stderr)
        traceback_text = traceback.format_exc()
        error_entry = f"ERROR: {exc}\n{error_log}\n--- TRACEBACK ---\n{traceback_text}"
        job.log = (previous_log + "\n---\n" + error_entry).strip() if previous_log else error_entry
    finally:
        job.save()
        shutil.rmtree(tmpdir, ignore_errors=True)


@shared_task
def run_similarity_job(job_id: int, smiles: str) -> None:
    job = models.ChemJob.objects.get(pk=job_id)
    tmpdir = Path(tempfile.mkdtemp(prefix="chem_sim_"))
    previous_log = job.log or ""
    try:
        output_path, stdout, stderr = utils.run_similarity_search(
            smiles=smiles,
            out_csv=tmpdir,
        )
        new_log = _compose_log(stdout, stderr)
        job.log = (previous_log + "\n---\n" + new_log).strip() if previous_log else new_log
        if output_path and output_path.is_file():
            job_dir = _job_media_dir(job.pk)
            version = len(list(job_dir.glob("sim_*.csv"))) + 1
            filename = f"sim_{job.pk}.csv" if version == 1 else f"sim_{job.pk}_v{version}.csv"
            dest = job_dir / filename
            job.out_csv.name = _store_file(output_path, dest)
    except Exception as exc:  # pragma: no cover
        error_entry = f"ERROR: {exc}"
        job.log = (previous_log + "\n---\n" + error_entry).strip() if previous_log else error_entry
    finally:
        job.save()
        shutil.rmtree(tmpdir, ignore_errors=True)
