from __future__ import annotations

import shutil
import tempfile
import traceback
from pathlib import Path
from typing import Iterable

from celery import shared_task
from django.conf import settings

from . import models, utils


def _job_media_dir(job_id: int) -> Path:
    base = Path(settings.MEDIA_ROOT) / "chem" / str(job_id)
    base.mkdir(parents=True, exist_ok=True)
    return base


def _ensure_placeholder_thumbnail(dest: Path) -> None:
    if dest.exists():
        return
    placeholder = (
        b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x08\x00\x00\x00\x08\x08\x06\x00\x00\x00\xc4\x0f\xbe\x8b"
        b"\x00\x00\x00\x06bKGD\x00\xff\x00\xff\x00\xff\xa0\xbd\xa7\x93\x00\x00\x00\x19tEXtSoftware\x00Generated by MM Portal\x00\x00\x00uIDATX\xc3c`\x18\x05\xa3`\x14\x8c\x02\x00\x07\x18\x02\x17\xc3\x8d\x9c<\x00\x00\x00\x00IEND\xaeB`\x82"
    )
    dest.write_bytes(placeholder)


def _next_versioned_path(directory: Path, stem: str, suffix: str) -> Path:
    suffix = suffix if suffix.startswith(".") else f".{suffix}"
    highest = 0
    for path in directory.glob(f"{stem}_v*{suffix}"):
        try:
            version_text = path.stem.rsplit("_v", 1)[1]
            highest = max(highest, int(version_text))
        except (IndexError, ValueError):
            continue
    return directory / f"{stem}_v{highest + 1}{suffix}"


def _store_file(src: Path, dest: Path) -> str:
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists():
        dest.unlink()
    shutil.move(str(src), str(dest))
    return dest.relative_to(Path(settings.MEDIA_ROOT)).as_posix()


def _merge_logs(previous: str, entries: Iterable[str]) -> str:
    new_entry = "\n---\n".join(part.strip() for part in entries if part and part.strip())
    if not new_entry:
        return previous
    return f"{previous.strip()}\n---\n{new_entry}" if previous else new_entry


def _error_entry(exc: Exception, detail: str = "") -> str:
    pieces = [f"ERROR: {exc}"]
    if detail:
        pieces.append(detail)
    pieces.append("--- TRACEBACK ---")
    pieces.append(traceback.format_exc())
    return "\n".join(pieces)


def _append_log(job: models.ChemJob, previous: str, entries: Iterable[str]) -> None:
    job.log = _merge_logs(previous, entries)


def _run_setup(logs: list[str]) -> None:
    for runner in (utils.run_settings_generator, utils.run_paths_generator):
        result = runner()
        if result:
            logs.append(result)


@shared_task
def run_drug_params_job(job_id: int, smiles: str, cid: str) -> None:
    job = models.ChemJob.objects.get(pk=job_id)
    tmpdir = Path(tempfile.mkdtemp(prefix="chem_drug_"))
    previous_log = job.log or ""
    logs: list[str] = []
    try:
        job.update_progress(10, "Initializing pipeline...")
        _run_setup(logs)
        
        job.update_progress(30, "Fetching molecular data...")
        output_path, stdout, stderr = utils.run_drug_parameter_evaluator(
            smiles=smiles or None,
            cid=cid or None,
            outdir=tmpdir,
        )
        
        job.update_progress(70, "Calculating properties...")
        logs.append(utils._compose_logs(stdout, stderr) or "(no output captured)")
        
        if output_path and output_path.is_file():
            job.update_progress(90, "Saving results...")
            job_dir = _job_media_dir(job.pk)
            dest = _next_versioned_path(job_dir, f"drug_{job.pk}", ".html")
            job.out_html.name = _store_file(output_path, dest)
        
        job.update_progress(100, "Completed!")
    except Exception as exc:  # pragma: no cover - defensive
        detail = ""
        if isinstance(exc, utils.ToolRunError):
            detail = utils._compose_logs(exc.stdout, exc.stderr)
        logs.append(_error_entry(exc, detail))
        job.update_progress(0, "Failed")
    finally:
        _append_log(job, previous_log, logs)
        job.save()
        shutil.rmtree(tmpdir, ignore_errors=True)


@shared_task
def run_binding_viz_job(job_id: int, pdb_id: str, ligand: str) -> None:
    job = models.ChemJob.objects.get(pk=job_id)
    tmpdir = Path(tempfile.mkdtemp(prefix="chem_bind_"))
    previous_log = job.log or ""
    logs: list[str] = []
    job_dir = _job_media_dir(job.pk)
    try:
        job.update_progress(10, "Initializing visualization...")
        _run_setup(logs)
        
        job.update_progress(30, f"Downloading PDB structure {pdb_id}...")
        output_path, stdout, stderr = utils.run_binding_visualizer(
            pdb_id=pdb_id,
            ligand=ligand or None,
            outdir=tmpdir,
        )
        
        job.update_progress(60, "Rendering 3D structure...")
        logs.append(utils._compose_logs(stdout, stderr) or "(no output captured)")
        
        if output_path and output_path.is_file():
            job.update_progress(80, "Saving visualization...")
            dest = _next_versioned_path(job_dir, f"binding_{pdb_id}", ".html")
            job.out_html.name = _store_file(output_path, dest)

        job.update_progress(90, "Generating thumbnail...")
        snapshot_path = tmpdir / f"{pdb_id}_structure.png"
        thumb_dest = job_dir / "thumb.png"
        if snapshot_path.exists():
            _store_file(snapshot_path, thumb_dest)
        else:
            _ensure_placeholder_thumbnail(thumb_dest)
        
        job.update_progress(100, "Completed!")
    except Exception as exc:  # pragma: no cover - defensive
        detail = ""
        if isinstance(exc, utils.ToolRunError):
            detail = utils._compose_logs(exc.stdout, exc.stderr)
        logs.append(_error_entry(exc, detail))
        _ensure_placeholder_thumbnail(job_dir / "thumb.png")
        job.update_progress(0, "Failed")
    finally:
        _append_log(job, previous_log, logs)
        job.save()
        shutil.rmtree(tmpdir, ignore_errors=True)


@shared_task
def run_similarity_job(job_id: int, smiles: str) -> None:
    job = models.ChemJob.objects.get(pk=job_id)
    tmpdir = Path(tempfile.mkdtemp(prefix="chem_sim_"))
    previous_log = job.log or ""
    logs: list[str] = []
    try:
        job.update_progress(10, "Initializing similarity search...")
        _run_setup(logs)
        
        job.update_progress(30, "Generating molecular fingerprint...")
        output_path, stdout, stderr = utils.run_similarity_search(
            smiles=smiles,
            out_csv=tmpdir,
        )
        
        job.update_progress(60, "Searching database for similar compounds...")
        logs.append(utils._compose_logs(stdout, stderr) or "(no output captured)")
        
        if output_path and output_path.is_file():
            job.update_progress(90, "Saving results...")
            job_dir = _job_media_dir(job.pk)
            dest = _next_versioned_path(job_dir, f"sim_{job.pk}", ".csv")
            job.out_csv.name = _store_file(output_path, dest)
        
        job.update_progress(100, "Completed!")
    except Exception as exc:  # pragma: no cover - defensive
        detail = ""
        if isinstance(exc, utils.ToolRunError):
            detail = utils._compose_logs(exc.stdout, exc.stderr)
        logs.append(_error_entry(exc, detail))
        job.update_progress(0, "Failed")
    finally:
        _append_log(job, previous_log, logs)
        job.save()
        shutil.rmtree(tmpdir, ignore_errors=True)
